### ISSUE TITLE
no campaigns show up on homepage node edit view

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5195] opened 2015-09-23 14:11 UTC
oddly though campaigns still show up on the homepage.

note: this is the US-English translation.

These nodes should also show up when starting a translated version (same as how the copy from fields copies over into a translation on campaign nodes).

![image](https://cloud.githubusercontent.com/assets/6330971/10047190/e83793f6-61da-11e5-869d-4e07c281a216.png)

**Comment by angaither** [comment] 2015-09-23 14:13
I noticed this, if you click 'add' they showed up for me, are you seeing the same thing?

**Comment by mikefantini** [comment] 2015-09-23 14:24
hmm this didn't work for me. I went to add a the Global English translation, which I saved, and I'm still seeing both the Global English translation blank AND the US English translation blank for the campaign field reference.

Also as a BR Admin, when I go to click Edit on the homepage, it also shows me the edit form with blank fields for the campaign field reference.

Added Global English translation as an administrator:

![image](https://cloud.githubusercontent.com/assets/6330971/10047580/dd6f0ff6-61dc-11e5-94f0-f18ee5ce851b.png)

No campaigns in the campaign field reference for the Global English translation:

![image](https://cloud.githubusercontent.com/assets/6330971/10047606/f1fbe430-61dc-11e5-8693-f833d4b7627c.png)

No campaigns in the campaign field reference for the US English translation:

![image](https://cloud.githubusercontent.com/assets/6330971/10047633/084bc034-61dd-11e5-9cd0-53b96d92e71a.png)

And when I click Edit on the homepage as a Brazilian admin to create a BR-PT translation, the campaign field reference is also blank:

![image](https://cloud.githubusercontent.com/assets/6330971/10047677/331d3fcc-61dd-11e5-8b01-223d19de8736.png)

**Comment by mikefantini** [comment] 2015-09-23 14:24
also note that subtitle is also blank in all situations. Only Title and Sponsors (which isn't translatable currently) are populated.

**Comment by mikefantini** [comment] 2015-09-23 14:26
@angaither I think @sergii-tkachenko did something special for the content in the fields to be copied over when creating a translation. Since you mentioned that Title field is all the same regardless of the node perhaps this is why Title is the only field that has copied content over?

**Comment by angaither** [comment] 2015-09-25 14:08
just updates, I can't reproduce this locally for either mx admin or us admin, with my site in english. 
up next: changing my site default to global english

**Comment by angaither** [comment] 2015-09-25 16:09
meh, still can't reproduce this on dev.

**Comment by mshmsh5000** [comment] 2015-09-25 16:14
On Thor, I see campaigns assigned to the `und` and `pt-br` translations.

![home-pt-und](https://cloud.githubusercontent.com/assets/149811/10105827/def2718a-637e-11e5-90ff-e9067798fd3f.png)

I think the base language change has left the assignments in `und` without copying them to the new translation variants (`en-us`, `en-global`).

**Comment by mshmsh5000** [comment] 2015-09-25 16:17
Consistent with other buggy behavior: https://thor.dosomething.org/br/ loads the `pt-br` campaign associations, which are obviously stored, but these don't show up on https://thor.dosomething.org/node/1141/edit/pt-br

**Comment by mshmsh5000** [comment] 2015-09-25 16:19
Also note that I can load the `pt-br` translation by entering the bare URL

https://thor.dosomething.org/node/1141/edit/pt-br

But the `translate` tab isn't showing up:

![no-translate](https://cloud.githubusercontent.com/assets/149811/10105931/a6a36752-637f-11e5-8066-3ba51fde0eb9.png)

Did we lose something during today's Thor deploys?

**Comment by angaither** [comment] 2015-09-25 16:20
@mshmsh5000 if you're a regional admin, the [translate tab should be hidden](https://github.com/DoSomething/phoenix/issues/5191)

**Comment by mshmsh5000** [comment] 2015-09-25 16:25
@angaither I see it on campaign nodes, but not on the homepage node:

![translate-campaigns](https://cloud.githubusercontent.com/assets/149811/10106067/7942793c-6380-11e5-8959-eba17472d9f8.png)

**Comment by angaither** [comment] 2015-09-28 14:22
@mikefantini pulled down the latest stage db, so it looks wonky on my local finally :+1:

**Comment by mikefantini** [comment] 2015-09-28 14:27
sweet!

**Comment by angaither** [comment] 2015-09-28 14:56
a fun update: I did a cache clear and the campaigns showed up. (on dev)
the subtitle did not, but I think that's because the language is und.

**Comment by angaither** [comment] 2015-09-28 15:11
@mikefantini how I "fixed" this

1) went to `node/1165/edit`
- saw blank pages

2) cleared cache
- still blank

3) went to `node/1165/translate`
4) clicked `edit` on english version
- saw content

5) went to `node/1165/edit`
- saw content

@mikefantini can you confirm?

**Comment by angaither** [comment] 2015-09-28 15:33
leaving this open till we deploy to prod and do this on prod

**Comment by angaither** [comment] 2015-09-29 14:32
may be fixed after #5276 is done

(cc @sergii-tkachenko)

**Comment by mikefantini** [comment] 2015-09-30 14:01
just an update this worked for me when doing on staging with the production database

**Comment by mshmsh5000** [comment] 2015-09-30 14:04
:100:

**Comment by angaither** [comment] 2015-10-01 16:07
we've deployed to prod now, are we ok closing this? @mikefantini 
I see both edit/translate on home page nodes and there are campaigns in the the reference fields.

**Closed as completed** 2015-10-01 22:42 UTC
Labels: bug, #homepage, #translation
