### ISSUE TITLE
Errors on campaign node_save() as admin

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#5048] opened 2015-09-09 13:56 UTC
`Warning: array_key_exists(): The first argument should be either a string or an integer in drupal_array_get_nested_value() (line 6774 of /var/www/dev.dosomething.org/html/includes/common.inc).`

when you save a campaign node as a brazil/mexico admin getting tons of these errors on the global branch.
this seems to be the offending code

```
    foreach ($fields as $field_name => $field) {
      $field_info = field_info_field($field_name);
      // If the field is not translatable disable access
      if (!$field_info['translatable']) {
        $form[$field_name]['#access'] = FALSE;
      }
    }
```

**Comment by itsjoekent** [comment] 2015-09-10 19:14
weird, thats the same code sergii wrote in the strong-arm, figured it would work :ok: 

Ill investigate in a few minutes!

**Comment by mikefantini** [comment] 2015-09-10 21:43
@angaither @deadlybutter is this possibly related to #5061?

**Comment by itsjoekent** [comment] 2015-09-11 14:59
Commented that part of the code out, getting a different error instead now? 

```
EntityMetadataWrapperException: Unknown data property field_description. in EntityStructureWrapper->getPropertyInfo() (line 335 of /var/www/dev.dosomething.org/html/profiles/dosomething/modules/contrib/entity/includes/entity.wrapper.inc).
```

EDIT: Actually ignore that, the line which seems to be the problem is line 65 $form[$field_name]['#access'] = FALSE;

EDIT: Logged the is_string($field_name) value and it was true for each field. Hmm...

EDIT: Even doing this causes the error $form['field_action_type']['#access'] = FALSE;

So its something with the first parameter (field_name) b/c removing that is when the error stops. However, replacing it with a valid static string, or casting the var to a string, (even though we verified with is_string that its in fact a string), we still dont resolve the issue.

**Comment by angaither** [comment] 2015-09-11 15:50
@deadlybutter normally caused by trying to get a field that doesn't exist. 
1. make sure your features are all reverted
2. check out [old issues, we've seen this quite a bit](https://github.com/DoSomething/phoenix/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+EntityMetadataWrapperException)

**Comment by itsjoekent** [comment] 2015-09-11 15:53
the field has to exist though, these are the fields which have been marked as translated. I can double check this but I dont think its the problem.

Ill check the old issues you linked and see how people closed em!

**Comment by itsjoekent** [comment] 2015-09-11 18:56
all of those issues involved a EntityMetadataWrapperException but seemed to be unrelated :/

also logged all of the field names, none of them are null/non existing (even though as I said before, I doubt any of these specific ones are because this code is only running on fields marked as translatable, so recently modified).

the only major discrepancy I see one of the field names is #parents instead of field_whatever , but that shouldn't cause 341 errors to pop up (just counted them all w/ jquery).

**Comment by itsjoekent** [comment] 2015-09-11 19:45
Yeah I'm not entirely sure whats going on here @angaither -- can we walk through this when you're in the office on Monday? Maybe I'm missing something

**Closed as completed** 2015-09-14 18:38 UTC
Labels: bug, @bender, priority-high, #global, #translation
