### ISSUE TITLE
Anonymous user from Japan gets 404'd on GL EN link of published campaign

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5530] opened 2015-10-16 20:22 UTC
This campaign is published and has a GL EN translation published as well https://thor.dosomething.org/campaigns/out-closet-cards-gl. However, when I go to that link as an anonymous user from Japan, I get a 404:

![image](https://cloud.githubusercontent.com/assets/6330971/10552459/e9d0d6a6-7421-11e5-857d-2a544f822b8d.png)

possibly related to #5528?

**Comment by angaither** [comment] 2015-10-19 18:35
duplicate of #5541

**Closed as completed by angaither** 2015-10-19 18:35 UTC
Labels: bug, @bender, priority-high, #global
