### ISSUE TITLE
Thor users (US, GL, BR, MX) are not going into Mailchimp

### ISSUE THREAD

**Issue by marahml** [DoSomethingArchive/legacy-website#5499] opened 2015-10-15 19:38 UTC
**BLOCKED by**:
- https://github.com/DoSomething/phoenix/issues/5635

**Issue Summary**:
The `user_country` is used to determine which MailChimp account to submit the email address to. An invalid `user_country` will result in submissions to the wrong MailChimp account resulting in:

```
(
    [status] => error
    [code] => 200
    [name] => List_DoesNotExist
    [error] => Invalid MailChimp List ID: 66fd18c5a9
)
```
- `user_country` set as `US` for Brazilian user, should be `BR`.
  - ~~Known bug~~, See https://github.com/DoSomething/phoenix/issues/5496

---

**Test Cases**:
- [ ] **Global users should go here**: 
  DS US Mailchimp Account > List: International
- [ ] **BR users should go here**: 
  BR Mailchimp Account > List: DoSomething Brazil
  - **Example payload**:

```
Array
(
    [activity] => user_register
    [email] => agaither+brazil@dosomething.org
    [uid] => 3118670
    [user_language] => en
    [user_country] => BR
    [merge_vars] => Array
        (
            [MEMBER_COUNT] => 4.2 million
            [FNAME] => Brazil
        )
    [email_template] => mb-user-register-US
    [mailchimp_list_id] => 66fd18c5a9
    [birthdate] => 915408000
    [subscribed] => 1
    [email_tags] => Array
        (
            [0] => drupal_user_register
        )
    [activity_timestamp] => 1444935634
    [application_id] => US
)
```
- serialized:

```
a:13:{s:8:"activity";s:13:"user_register";s:5:"email";s:31:"agaither+brazil@dosomething.org";s:3:"uid";s:7:"3118670";s:13:"user_language";s:2:"en";s:12:"user_country";s:2:"BR";s:10:"merge_vars";a:2:{s:12:"MEMBER_COUNT";s:11:"4.2 million";s:5:"FNAME";s:6:"Brazil";}s:14:"email_template";s:19:"mb-user-register-US";s:17:"mailchimp_list_id";s:10:"66fd18c5a9";s:9:"birthdate";s:9:"915408000";s:10:"subscribed";i:1;s:10:"email_tags";a:1:{i:0;s:20:"drupal_user_register";}s:18:"activity_timestamp";i:1444935634;s:14:"application_id";s:2:"US";}
```
- [ ] **MX users should go here**: 
  MX Mailchimp Account > List: DoSomething Mexico 
- [x] **This is working properly for U.S. users**

```
Array
(
    [activity] => user_register
    [email] => lidey.marah+usa@gmail.com
    [uid] => 3118674
    [user_language] => en
    [user_country] => US
    [merge_vars] => Array
        (
            [MEMBER_COUNT] => 4.2 million
            [FNAME] => Marandrea
        )
    [email_template] => mb-user-register-US
    [mailchimp_list_id] => f2fab1dfd4
    [birthdate] => 620611200
    [subscribed] => 1
    [email_tags] => Array
        (
            [0] => drupal_user_register
        )
    [activity_timestamp] => 1444936362
    [application_id] => US
)
```
- serialized:

```
a:13:{s:8:"activity";s:13:"user_register";s:5:"email";s:25:"lidey.marah+usa@gmail.com";s:3:"uid";s:7:"3118674";s:13:"user_language";s:2:"en";s:12:"user_country";s:2:"US";s:10:"merge_vars";a:2:{s:12:"MEMBER_COUNT";s:11:"4.2 million";s:5:"FNAME";s:9:"Marandrea";}s:14:"email_template";s:19:"mb-user-register-US";s:17:"mailchimp_list_id";s:10:"f2fab1dfd4";s:9:"birthdate";s:9:"620611200";s:10:"subscribed";i:1;s:10:"email_tags";a:1:{i:0;s:20:"drupal_user_register";}s:18:"activity_timestamp";i:1444936362;s:14:"application_id";s:2:"US";}
```

**Comment by mikefantini** [comment] 2015-10-16 16:59
@marahml @DeeZone I just tested with a bunch of users and I wasn't seeing _any_ users going into the appropriate MailChimp buckets regardless of where they were located; i.e. even US users weren't going into the DoSomething Members list on the DS US MailChimp account.

This is however working on production for US users.

**Comment by deezone** [comment] 2015-10-16 17:17
@marahml @mikefantini I have this consumer shut down as I debug it. There's no point testing it further until I set up again.

**Comment by marahml** [comment] 2015-10-21 14:34
@DeeZone just checking in on this! Let me know when I can help with testing. Thanks Dee!

**Comment by deezone** [comment] 2015-10-22 14:21
@marahml Once https://github.com/DoSomething/phoenix/pull/5579 PR is merged this issue should be resolved and ready for testing.

**Comment by marahml** [comment] 2015-10-26 16:27
- Tested as a BR user on Thor, and my email (mlidey+brazil1026@dosomething.org) did not go into the DoSomethingBrazil Mailchimp account @DeeZone.
- Tested as an MX user on Thor, and my email (mlidey+mexico1026@dosomething.org) did not go into the DoSomethingMexico Mailchimp account either.
- GL email addresses are going into US Mailchimp Account > DS members. But they should be going into US Mailchimp Account > International. Tested with mlidey+global1026@dosomething.org.

**Comment by mikefantini** [comment] 2015-10-26 16:31
@marahml Did your BR/MX users also end up in the US MailChimp account? Or are they just nowhere to be found in MailChimp?

**Comment by marahml** [comment] 2015-10-26 17:45
@mikefantini couldn't find the BR/MX users anywhere unfortunately

**Comment by deezone** [comment] 2015-10-26 20:48
@marahml @mikefantini Looking in the Mexico MailChimp account. It appears the signup worked. Note, the addition of the account if via the MailChimp API. Batch submissions can take to process on the MailChimp. Please allow up to 10 minutes before assuming the submission didn't work:

**Mexico**
![image](https://cloud.githubusercontent.com/assets/2119264/10742018/4f0329ac-7c01-11e5-9766-d607ae6913e1.png)

**Comment by deezone** [comment] 2015-10-26 23:50
@marahml The issue is with your test users not resolving to the country you're expecting. An example is your international test where your global user **mlidey+Global1026@dosomething.org** has a language and country setting that does not reflect an international user thus the reason the expected mail MailChimp list is not being updated.

```
    [user_language] => en
    [email_template] => mb-user-register-US
```

Full payload example of test submission:

```
(
    [activity] => user_register
    [email] => mlidey+Global1026@dosomething.org
    [uid] => 3118813
    [merge_vars] => Array
        (
            [MEMBER_COUNT] => 4.2 million
            [FNAME] => Marah
        )

    [user_country] => US
    [user_language] => en
    [email_template] => mb-user-register-US
    [mailchimp_list_id] => f2fab1dfd4
    [birthdate] => 620611200
    [subscribed] => 1
    [email_tags] => Array
        (
            [0] => drupal_user_register
        )

    [activity_timestamp] => 1445876464
    [application_id] => US
)
```

Can we run these tests together to ensure they're in fact from the country you're expecting.

cc @mikefantini

**Comment by marahml** [comment] 2015-10-27 14:23
I logged in w/ TorGaurd as a user from Japan so not sure what the issue might be.

Good find on Mexico @DeeZone. That's great!

Still not seeing a user in the Mailchimp BR account

**Comment by deezone** [comment] 2015-10-27 14:38
@marahml 

> Can we run these tests together to ensure they're in fact from the country you're expecting.

**Comment by deezone** [comment] 2015-10-27 16:07
Confirmed, US, BR and MX signups result in MailChimp entries.

Bug: Global users are not including a `mailchimp_list_id` in the transactional message. Related issue: https://github.com/DoSomething/phoenix/issues/5635

**Closed as completed** 2015-10-28 15:23 UTC
Labels: #message-broker, #global, BLOCKED
