### ISSUE TITLE
Videos on 404 page look wrong

### ISSUE THREAD

**Issue by sergiitk** [DoSomethingArchive/legacy-website#5304] opened 2015-09-29 15:04 UTC
Videos on 404 page (ex., with the Sloth and Bigfoot) occupy more place than intended.
Link: https://www.dosomething.org/node/5757, hit refresh few times.
Browser: Chrome Version 46.0.2490.42 beta (64-bit)
![image](https://cloud.githubusercontent.com/assets/672669/10168164/3a5a4efa-66d4-11e5-9c90-880181e12c06.png)

сс @deadlybutter @DFurnes

**Comment by DFurnes** [comment] 2015-09-29 15:07
Having trouble reproducing this in Chrome 45:

![screen shot 2015-09-29 at 11 06 15 am](https://cloud.githubusercontent.com/assets/583202/10168315/3fbe9ba6-669a-11e5-88d7-93059956b7ed.png)

@sergii-tkachenko Do you see any errors in the web console?

**Comment by DFurnes** [comment] 2015-09-29 15:08
Oh, never mind. Just re-read the issue, and am able to reproduce in Chrome Canary. Blargh.

**Comment by DFurnes** [comment] 2015-09-29 15:19
Related [issue on the Chrome bug tracker](https://code.google.com/p/chromium/issues/detail?id=536854) and [patch](https://codereview.chromium.org/1370363002). Going to close this since it's not an issue on our end. Thanks for the bug report, @sergii-tkachenko!

**Closed as completed by DFurnes** 2015-09-29 15:19 UTC
Labels: bug, @fender
