### ISSUE TITLE
Issues with Campaign Collections on Staging

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5647] opened 2015-10-27 23:43 UTC
- Edited https://staging.dosomething.org/volunteer/grandparents-gone-wired
- Cleared cache
- Received this error

![image](https://cloud.githubusercontent.com/assets/6330971/10775808/24c87908-7ce2-11e5-808d-e170a79aea7a.png)

I did the above steps because I was trying to figure out why so little of the content for the collection is showing up:

![image](https://cloud.githubusercontent.com/assets/6330971/10775892/d82df6d0-7ce2-11e5-8519-4c4f29652007.png)

Even though way more fields are filled out:

![image](https://cloud.githubusercontent.com/assets/6330971/10775864/a972990e-7ce2-11e5-860c-2dcf544254be.png)

![image](https://cloud.githubusercontent.com/assets/6330971/10775875/bb3d4134-7ce2-11e5-9c91-04b6ef2f2df4.png)

Assigned to @angaither for now, but @DFurnes @sergii-tkachenko not sure if either of you know what's going on?

**Comment by mikefantini** [comment] 2015-10-28 13:44
Potentially related to #5433

**Comment by sergiitk** [comment] 2015-10-28 14:07
Hi @mikefantini! Yes, yesterday I noticed this when was working on #5433. However, these two bugs are not related. To be precise, this error
![image](https://cloud.githubusercontent.com/assets/6330971/10378143/3f8b165e-6dd5-11e5-8f1f-1aea66d77c57.png)
you reported in #5433 related to this bug, but not to #5433.

The strangest thing about this bug is that this works on local dev, but not on staging (even though the same DB is used). I will investigate this today.

**Comment by sergiitk** [comment] 2015-10-28 14:31
To compare: local and staging, same DB:
![image](https://cloud.githubusercontent.com/assets/672669/10791496/4f43fb6c-7d91-11e5-9b84-b6ec89441d5c.png)

**Comment by sergiitk** [comment] 2015-10-28 14:36
Ok, I noticed the difference now. I was logged in staging.
Anonymous can see campaigns on staging just fine:

![image](https://cloud.githubusercontent.com/assets/672669/10791639/eef5e3d2-7d91-11e5-96fa-75a1197034b6.png)

**Comment by sergiitk** [comment] 2015-10-28 14:42
Hm. After I opened this as an anonymous I can't reproduce this bug on staging anymore. Neither logged in nor anonymously.

**Comment by mikefantini** [comment] 2015-10-28 14:47
@sergii-tkachenko I opened up an incognito window and am seeing all of the content correctly as an anonymous user.

![image](https://cloud.githubusercontent.com/assets/6330971/10791985/2e37cb54-7d61-11e5-9319-11e59ff31b62.png)

When I open it in my normal Chome window still logged in as an admin I'm still seeing the errors and missing content:

![image](https://cloud.githubusercontent.com/assets/6330971/10791994/3eac5ba8-7d61-11e5-9da0-88be5c50bdf1.png)

![image](https://cloud.githubusercontent.com/assets/6330971/10792012/480e66a0-7d61-11e5-9363-e98645f311df.png)

**Comment by mikefantini** [comment] 2015-10-28 14:48
Also now seeing this error as an anonymous user on the homepage:

![image](https://cloud.githubusercontent.com/assets/6330971/10792034/67f098da-7d61-11e5-9e4b-1d6fbe544138.png)

cc: @DFurnes

**Comment by sergiitk** [comment] 2015-10-28 14:49
@mikefantini That error been there for a long time. Actually, let me fix it quickly so it doesn't confuse us anymore.

**Comment by sergiitk** [comment] 2015-10-28 15:00
The warning in campaign group template fixed in #5651.

**Comment by sergiitk** [comment] 2015-10-28 20:12
It turned out that this happens for users which have language preference other than `en`.
About 1330 users in production database have non-english language in their profile settings and are affected with this bug.

**Closed as completed** 2015-10-29 14:07 UTC
Labels: bug, BLOCKER, priority-high, #campaign-collections
