### ISSUE TITLE
Recorded Birthday One Day Early in Mailchimp

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5840] opened 2015-11-24 18:35 UTC
For some reason, if you look at the recorded birthdays in Drupal vs. in Mailchimp, Mailchimp shows a date one day before the birthday listed in Drupal.

I'm not sure how long this has been happening for (my admin account appears correctly in Mailchimp, or example), but the discrepancy can be viewed by searching for the emails of the most recent users shown here (https://www.dosomething.org/admin/users) in Mailchimp.

Not sure what we might use the Mailchimp data for, so not sure if this is actually a problem or not, but thought I would flag!

**Comment by marahml** [comment] 2015-11-25 15:55
Oof good to know @namimody. Thanks for flagging! Assigning to Dee to investigate as something that is low priority but we def want to figure out

**Comment by deezone** [comment] 2015-11-25 17:46
**Note to self**:
- https://www.dosomething.org/us/user/3335148
  - Birthdate in Drupal: 01/12/1993
  - Birthdate in MailChimp: 01/11/1993
  - Birthdate in `mb-users` database: 1993-01-12T00:00:00.000Z

Looks like the issue is specific to the submission of the date to MailChimp specifically. This supported by the Message Broker user database having the correct date.

**Theories**: 
- A time zone difference between the `birthdate_timestamp` value submitted and the MailChimp server.
- Bug in MailChimp API `batch-subscribe` endpoint

Understood this is low priority but I suspect it's the first sign of how we've not considered timezones in our development. Being global this might be an issue going forward.

cc: @namimody @marahml

**Closed as completed** 2016-08-08 18:00 UTC
Labels: bug, #message-broker, #data-engineering, NO
