### ISSUE TITLE
Cannot Update Campaign Collections

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5341] opened 2015-10-01 21:08 UTC
While https://www.dosomething.org/volunteer/old-school-impact has campaigns as part of the collection, the edit tab (https://www.dosomething.org/node/4953/edit) shows no campaigns, so leads cannot edit the collection.

![image](https://cloud.githubusercontent.com/assets/12396076/10233824/faec3dbe-685e-11e5-88c2-d19d3e6f5bb7.png)

@sergii-tkachenko could this be related to https://github.com/DoSomething/phoenix/issues/5195 -- both have campaign field reference? if so, will it be fixed when https://github.com/DoSomething/phoenix/pull/5315 is deployed? Thanks!!

**Comment by namimody** [comment] 2015-10-05 20:36
@mikefantini @sergii-tkachenko Adam needs to show this to AARP the week of the 19th, so would be great to have this all fixed by the 15th (a Thursday) if possible!

**Comment by sergiitk** [comment] 2015-10-07 20:46
Looking at this.

**Comment by sergiitk** [comment] 2015-10-07 21:05
1. Looks like it's related to #5195
2. Not sure if Home page was fixed manually or programmatically #5315 cc @mikefantini 
3. Investigating the reason behind this

**Comment by sergiitk** [comment] 2015-10-07 21:23
I just confirmed that executing script from #5315 fixed the issue on staging: http://staging.beta.dosomething.org/node/1194/edit.

I think we should run in on prod. Will coordinate this with @sheyd.

**Comment by sergiitk** [comment] 2015-10-13 17:48
Fixed in https://github.com/DoSomething/phoenix/issues/5276#issuecomment-147792473.

**Closed as completed by sergiitk** 2015-10-13 17:48 UTC
Labels: bug, @bender, #campaign-collections
