### ISSUE TITLE
Translation status pulling in impossible number of translations

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5559] opened 2015-10-20 20:00 UTC
https://thor.dosomething.org/admin/content/search/translation?title=Momm-o-grams&type=campaign&field_cause_tid=All&status=All

![image](https://cloud.githubusercontent.com/assets/6330971/10619422/9bf462ac-7743-11e5-8ba0-ff6d0b6029a2.png)

**Comment by itsjoekent** [comment] 2015-11-02 15:33
cant reproduce?

**Comment by angaither** [comment] 2015-11-04 18:21
@mikefantini this looks ok to me now, closing out
![image](https://cloud.githubusercontent.com/assets/645205/10947624/fd4fb100-82f6-11e5-8bfc-26113c4e7447.png)

**Closed as completed by angaither** 2015-11-04 18:21 UTC
Labels: bug, #global, #translation
