### ISSUE TITLE
Global - Media Query polyfill not loading correctly

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1058] opened 2014-03-07 00:16 UTC
IE8 on XP, the "sign up" link shows up as 3 parallel lines, like in a mobile device, and nothing seems to happen when clicked. The user is blocked from signing up.

https://trello-attachments.s3.amazonaws.com/52ea92c7ccdaf8415b8cab3a/5319014aabaa4c6642f7be02/3c3aef0b07fba39eed6d4d2fcc480aad/dosomethingie8blockage.jpg

https://trello.com/c/IsAMVbal

**Comment by DFurnes** [comment] 2014-03-10 15:08
Looks like the media query polyfill isn't loading. Will look into this.

**Comment by DFurnes** [comment] 2014-03-13 20:41
So, the issue is that our rem unit polyfill isn't able to parse the stylesheets if they're added using `@import` in inline scripts like Drupal does (which makes sense when you consider how much more work parsing a ton of inline style includes would be).

The easiest solution here is probably just turning on CSS aggregation on stage. (Also not a bad idea, since that makes it closer to our production environment will be.)

/cc @mshmsh5000

**Comment by mshmsh5000** [comment] 2014-03-14 14:26
CSS aggregation enabled on stage.

**Comment by DFurnes** [comment] 2014-03-14 21:52
Marking as closed! :100:

**Closed as completed** 2014-03-14 21:52 UTC
Labels: bug, @fender, priority-high
