### ISSUE TITLE
Coder misconfigured? Possible work around with drush

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#431] opened 2014-01-21 23:36 UTC
As suggested in the wiki, https://github.com/DoSomething/dosomething/wiki/Contributing. Running:

codercs YOURFILE

produces the error:

ERROR: the "/profiles/dosomething/modules/contrib/coder/coder_sniffer/Drupal/ruleset.xml" coding standard is not installed. The installed coding standards are PEAR, MySource, PHPCS, Zend, Squiz, PSR1 and PSR2

As a work around, 

drush drupalcs YOURFILE

works. It appears a symlink to ruleset.xml is not setup?!?

**Comment by deezone** [comment] 2014-01-21 23:39
Further to this, from the admin interface the following is produced:
https://dev.dosomething.org:8889/admin/config/development/coder

Fatal error: Call to undefined method PHP_CodeSniffer::setTokenListeners() in /vagrant/html/profiles/dosomething/modules/contrib/coder/coder_review/includes/coder_review_sniffer.inc on line 88

**Comment by aaronschachter** [comment] 2014-01-22 03:25
This is a duplicate of #294

**Comment by barryclark** [comment] 2014-02-21 17:56
closing as it's a dup of #294

**Closed as completed by barryclark** 2014-02-21 17:56 UTC
