### ISSUE TITLE
Canada Users are still created with US address

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3307] opened 2014-11-03 21:57 UTC
Created an account on Canada prod, but when I go to edit my profile, I am still presented with the US states.  needs investigation but my guess is that the `field_address` value stored is using US and not CA.

**Comment by sergiitk** [comment] 2014-11-05 17:35
Are you sure guys that new users have `US` in `field_address`?
Here's last user registered on DS Canada production:

``` sql
SELECT field_address_country FROM field_data_field_address ORDER BY entity_id DESC LIMIT 1;
+-----------------------+
| field_address_country |
+-----------------------+
| CA                    |
+-----------------------+
1 row in set (0.00 sec)
```

**Comment by sergiitk** [comment] 2014-11-05 17:36
As I see last 12 users has `CA` country.

**Comment by sergiitk** [comment] 2014-11-05 17:41
Here's [user #1732915](https://canada.dosomething.org/user/1732915/edit) I just created. It has `CA` set as country:

``` sql
mysql> SELECT field_address_country FROM field_data_field_address WHERE entity_id=1732915;
+-----------------------+
| field_address_country |
+-----------------------+
| CA                    |
+-----------------------+
1 row in set (0.00 sec)
```

However, the address field still shows US states:
![image](https://cloud.githubusercontent.com/assets/672669/4922541/dd8f0f1c-6512-11e4-8c28-536b00903aba.png)

@aaronschachter, could you please check if field display set right?

**Comment by aaronschachter** [comment] 2014-11-05 17:49
Is this because of the settings on the `field_address` feature?   it prevents you from having a CA address?

**Comment by aaronschachter** [comment] 2014-11-05 17:49
Also, do you see Canada states in the "Send me stuff" form on https://canada.dosomething.org/campaigns/canada-schools-test ?   I am, which I actually don't understand how that's happening (I'm logged in as my admin account)

**Comment by sergiitk** [comment] 2014-11-05 17:59
On page https://canada.dosomething.org/campaigns/canada-schools-test new users see states of Canada!
![image](https://cloud.githubusercontent.com/assets/672669/4922849/87dab690-6515-11e4-8f97-b4818cd52135.png)

**Comment by sergiitk** [comment] 2014-11-05 18:00
@mikefantini Does it make this ticket closed?

**Comment by aaronschachter** [comment] 2014-11-05 18:01
Yeah this is weird.  I definitely saw this bug 2 days when I opened it.  yeah @mikefantini can you test too?

**Comment by sergiitk** [comment] 2014-11-05 18:04
@aaronschachter I think we should report new bug with country field on user edit form.

**Comment by aaronschachter** [comment] 2014-11-05 18:05
Yeah that makes sense, @sergii-tkachenko .  Can you please open it?  That issue will def not be critical for TFJ for launch.

**Comment by mikefantini** [comment] 2014-11-05 18:23
i'm still seeing state on https://canada.dosomething.org/campaigns/canada-schools-test for a user I _just_ created on production email mfantini+canada1@dosomething.org

![image](https://cloud.githubusercontent.com/assets/6330971/4923222/cf9c6bf6-6518-11e4-8bb3-a2e39fe7fe48.png)

**Comment by sergiitk** [comment] 2014-11-05 18:31
@mikefantini I think the issue is in the way you save the user when making it an administrator. I assume, thats when your country got reset to `US`. See issue #3328 
Let me just grant you admin role using drush.

**Comment by mikefantini** [comment] 2014-11-05 18:37
yup you're right @sergii-tkachenko closing this out now

**Closed as completed by mikefantini** 2014-11-05 18:37 UTC
Labels: bug, priority-high
