### ISSUE TITLE
Campaign Language Support

### ISSUE THREAD

**Issue by marahml** [DoSomethingArchive/legacy-website#5591] opened 2015-10-22 18:28 UTC
These need to be spec'd out into separate issues in various repos, by @DeeZone but summary: 

**mb-users Mongo Database Update for POSTs (saving language)**

Adding support for global users to receive the weekly digest email message. In order to support this functionality the user and campaign language setting will need to be supported.
- Support `user_language` and `user_country` in POST to `/user` in `mb-user-api`. 
  - Schema update to `mb-users` Mongo collection.
- Support `campaign_language` in POST to `/user` in `mb-user-api`for user campaign activity.
  - Schema update to `mb-users` Mongo collection.
- Support `user_language` and `user_country` in `mbc-userAPI-userRegister` consumer to process `user_register` transactions for POSTing to `mb-user-api` `/user`.
- Support `campaign_language` in `mbc-userAPI-campaignActivity` consumer to process `campaign_signup` transactions for POSTing to `mb-user-api` `/user`.

**Comment by deezone** [comment] 2015-11-03 21:37
Duplicate of #5601

**Closed as completed by deezone** 2015-11-03 21:37 UTC
Labels: #message-broker, #global, email-digest
