### ISSUE TITLE
Title and sub-title not flush on photo edge for campaigns with 'created by' feature

### ISSUE THREAD

**Issue by ngjo** [DoSomethingArchive/legacy-website#6693] opened 2016-07-07 20:26 UTC
#### Current Behavior

When you're on an action page of campaigns with a 'Created By' person, the title and sub-title are pushed up. Nami mentioned that this might have something to do with the changes to the sponsor logo that went live recently #6433 
#### Desired Behavior

Keeping the 'Created By' still, the title and sub-title should be flush against the bottom of the header photo, like https://www.dosomething.org/us/campaigns/party-animal.
#### Steps to Replicate
1. Go to https://www.dosomething.org/us/campaigns/bookmark-climate-change or https://www.dosomething.org/us/campaigns/paint-planet
#### Why This Matters

Not the intended design
#### Relevant Screenshots + Links

https://www.dosomething.org/us/campaigns/bookmark-climate-change

![screen shot 2016-07-07 at 10 28 17 am](https://cloud.githubusercontent.com/assets/2658867/16668217/2503f3d6-445e-11e6-8b58-e4e0debe3704.png)

![image](https://cloud.githubusercontent.com/assets/12396076/16670096/a2f0d59a-4466-11e6-86a1-6270e4bf90f2.png)

cc: @namimody

**Comment by sbsmith86** [comment] 2016-07-11 15:42
@ngjo Confused to this one as it seems like the solution for #6693 was to always have the logo at that bottom of the title and sub-title ( [looking at this discusstion](https://github.com/DoSomething/phoenix/issues/6433#issuecomment-228162723)]...so i'm not sure what the bug is exactly?

/cc @angaither @namimody @DFurnes

**Comment by ngjo** [comment] 2016-07-11 15:50
Hmmm, @namimody might be able to offer more insight into this one. She flagged the issue when we were doing some other training stuff -- @namimody ? Thanks!

**Comment by namimody** [comment] 2016-07-11 16:36
@sbsmith86 @ngjo @angaither @DFurnes 

Sorry for the confusion! This is a member-created campaign and I felt the spacing looked weird. This is what it used to look like:

![image](https://cloud.githubusercontent.com/assets/12396076/16738520/0786f71e-4764-11e6-82f5-ee37eb130b47.png)

Does that help clarify? Also happy to talk in person?

**Comment by DFurnes** [comment] 2016-07-11 16:43
Yep, like @sbsmith86 mentioned, the solution we discussed for #6433 fixed the issue where we couldn't make the sponsor logo wider (because it would overlap with the title/subtitle) by moving it onto it's own row below.

It's definitely not a bug, but it might be worth having another design pass if it doesn't look good.

**Comment by DFurnes** [comment] 2016-07-11 16:44
For some additional context, here's the PR where the fix was applied: #6648.

**Comment by namimody** [comment] 2016-07-11 17:18
@DFurnes do you mean another design pass for just MCC campaigns?

**Comment by DFurnes** [comment] 2016-07-11 17:26
If you don't think this looks good with the solution applied for #6433, then I think it makes sense for the design team to take another pass at figuring out how to fit all the things we have in the header together at each breakpoint.

**Comment by namimody** [comment] 2016-07-11 17:42
Cool, thanks all. I'll assign to @lkpttn then.

I guess we'll need to make solutions for pitch pages, action page, and closed states, with AND without campaign end dates and with the following combinations:
- [ ] no sponsor logo
- [ ] sponsor logo
- [ ] just a "created by" person
- [ ] sponsor logo + created by person
- [ ] two sponsor logos
- [ ] two sponsor logos + created by person

Apologies for not remembering the MCC variation earlier, team.

**Comment by DFurnes** [comment] 2016-07-11 19:33
I'm not a designer, so I'm sure @lkpttn will have a smarter solution than I was able to come up with. 

For whatever it's worth, I definitely don't think we should be creating separate variations of the header for each of these possible permutations. That's just layering on unnecessary complexity waiting to cause bugs later on.

**Comment by lkpttn** [comment] 2016-07-12 13:58
We have a significant redesign coming for the campaign template as a whole, so we might have radical changes coming that render a lot of these issues moot. I'm not super enthused to wrestle with this if the problem will disappear soon.

**Comment by namimody** [comment] 2016-07-12 14:07
Alright cool @lkpttn -- and seems to only be a problem with the handful of campaigns that are member created. Closing -- sorry all.

**Closed as completed by namimody** 2016-07-12 14:07 UTC
Labels: design-qa, #campaign-template
