### ISSUE TITLE
Logging out leads to a 404

### ISSUE THREAD

**Issue by lkpttn** [DoSomethingArchive/legacy-website#3845] opened 2015-01-30 15:08 UTC
Logging out from the homepage took me to https://www.dosomething.org/user/logout which currently 404s. We can have this direct you back to the homepage for now, or if it's possible take you back to where you were.

cc @mikefantini

**Comment by DFurnes** [comment] 2015-01-30 17:46
Just tried to log out on production and it just kept reloading on the same page, without logging me out. After a couple of tries, I opened "Log Out" link in new tab and it showed the 404 page & logged me out as reported above. Strange!

**Comment by mikefantini** [comment] 2015-01-30 18:26
FWIW: I just logged out (was an admin) from Comeback Clothes and got taken to the homepage

**Comment by aaronschachter** [comment] 2015-02-17 15:40
This seems to only happen when a role has the Admin toolbar. I've tested on prod as a non-staff role and everything works as expected. @DFurnes Were you logged in as an admin when you replicated?  I'm tempted to close this one since it doesn't affect end users (cc @barryclark @mikefantini )

**Comment by mikefantini** [comment] 2015-02-17 15:42
@lkpttn @DFurnes can you confirm whether this is happening for you as an admin or auth user?

If it's just happening for admins let's definitely close it.

**Comment by lkpttn** [comment] 2015-02-17 16:14
I tried it again as both an admin and regular user on staging and couldn't replicate it again.

**Comment by mikefantini** [comment] 2015-05-04 16:17
@Bladt and I are seeing this happening again.

I just tried to log out from https://www.dosomething.org/campaigns/comeback-clothes as a non-admin. First it just reloaded the page and nothing happened. I tried again on the reloaded page and am now getting logged out and redirected to /user/logout which 404s.

@DFurnes can you take a look?

**Comment by DFurnes** [comment] 2015-05-04 16:56
@aaronschachter @angaither Any ideas? Drupal internals are not my forte.

**Comment by angaither** [comment] 2015-05-04 17:13
@mikefantini I'm not able to recreate this on stage or prod... I've tried 5+ times

**Comment by mikefantini** [comment] 2015-05-04 18:09
hmmm I was just able to reproduce it again on the homepage:
- logged in as non-admin on homepage
- try to log out, page refreshes and I'm still logged in
- try to log out again, I get logged out but am taken to /user/logout which 404s

Seems to be happening pretty inconsistently. @blisteringherb @sheydari-ds might this be a web head thing?

**Comment by ghost** [comment] 2015-05-12 14:37
Took a look at all of the server and Varnish logs that 404 out, and the number of errors per overall requests is very low (~15 in the past 30 days or so, total). It's likely something we can fix with allowing certain URI's in Varnish to be "passed", but we'd have to test this first, and it's not a trivial change. Slated for investigation and testing post-migration.

**Comment by angaither** [comment] 2015-11-16 18:50
closing! 
@sheyd re-open if I'm wrong here, but I haven't seen this behavior anymore

**Closed as completed by angaither** 2015-11-16 18:50 UTC
Labels: bug, @bender
