### ISSUE TITLE
promoted reason/flagged not being saved

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#4658] opened 2015-07-02 22:23 UTC
- [reportback in question](https://www.dosomething.org/admin/reportback/48592) - RBID 48592
- [video](http://screencast.com/t/hkdyVf1Zze2x) watch at 0:21
- [campaign](https://www.dosomething.org/campaigns/mirror-messages) - NID 7

potentially related to #4529

**Comment by angaither** [comment] 2015-07-08 17:34
@deadlybutter could be related to the work you did with #4621

**Comment by itsjoekent** [comment] 2015-07-08 18:06
yeah just tried promoting it again and it didn't work. hmmmm. let me see if i can reproduce locally 

edit: wait... onto something

**Comment by itsjoekent** [comment] 2015-07-08 18:16
so promoting definitely works. just need to check the reason is being saved 

its showing up here:

<img width="572" alt="screen shot 2015-07-08 at 2 15 23 pm" src="https://cloud.githubusercontent.com/assets/897368/8578289/e7ea95e2-257b-11e5-8ac5-6bb49bcc63e7.png">

and it looks correct in the change log:

<img width="509" alt="screen shot 2015-07-08 at 2 15 33 pm" src="https://cloud.githubusercontent.com/assets/897368/8578298/f50e0e7a-257b-11e5-9b90-89c55eceeaa4.png">

**Comment by itsjoekent** [comment] 2015-07-08 20:11
Okay this is a bug _but_ I believe it's the same issue being experienced in #4529 as saving promoted reasons does work (I just checked on the production DB and it was given a promoted reason). 

@angaither do you agree this is a duplicate? can we close this and move discussion back into #4529 ?

**Comment by angaither** [comment] 2015-07-08 20:14
I _think_ this issue and #4529 are the same thing, but let's leave this open for now just for documentation and this is about reasons not saving, not about the boolean value.

**Comment by itsjoekent** [comment] 2015-07-08 20:14
okie dokes

**Comment by angaither** [comment] 2015-07-22 20:25
@deadlybutter can you take another stab at this?

I think the way forward might be adding the `flagged reason` to the `dosomething_reportback_log` 
I know it doesn't make sense with CRUD, but what if we added a `review` OP that stored what is being sent?
Then we can add the flagged reason to the table and update the cron from #4719 so we aren't loosing data

@aaronschachter I would love your input on this

**Comment by aaronschachter** [comment] 2015-07-22 21:03
Adding all review related updates (status, promoted/flagged reasons, etc) to the `dosomething_reportback_log` table sound like time well spent to me...

**Comment by angaither** [comment] 2015-07-23 13:17
great great great, thanks @aaronschachter :smile_cat:

**Closed as completed** 2015-07-23 19:37 UTC
Labels: bug
