### ISSUE TITLE
GL EN CTAs are appearing in PT on homepage for Brazilian user 

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5274] opened 2015-09-28 18:41 UTC
I'd start with this comment: https://github.com/DoSomething/phoenix/issues/5274#issuecomment-157096237

---
- logged in as user 2987505 (who has language set as BR PT)
- seeing campaign titles in PT (good)
- seeing CTAs in English (bad)
- when I use the finder, I'm seeing CTAs in PT (good)

homepage:
![image](https://cloud.githubusercontent.com/assets/6330971/10144884/11a67e20-65ee-11e5-9d72-c142ccfaf230.png)

filtered results on finder:
![image](https://cloud.githubusercontent.com/assets/6330971/10144895/22461704-65ee-11e5-8a5e-4e536576d192.png)

might be related to #5257? Which I kind of think we might not need because we really should have an editorial rule where a version of the homepage doesn't include campaigns that don't have a translation in the language of the homepage (i.e. we shouldn't have a MX-SP homepage that has a campaign that doesn't exist in MX-SP)

**Comment by mikefantini** [comment] 2015-10-02 14:16
updated experience:
- as user 2987614 (lang: BR PT) I'm seeing GL EN titles and BR PT CTAs on thor.dosomething.org before using the finder. since I'm on thor.dosomething.org (not thor.dosomething.org/br) this should be all GL EN.

![image](https://cloud.githubusercontent.com/assets/6330971/10256593/4c504382-6920-11e5-922c-be4d66227896.png)
- as user 2987614 (lang: BR PT) I'm seeing BR PT CTAs and BR PT CTAs in finder results on thor.dosomething.org. this should be all GL EN since i'm on thor.dosomething.org (not thor.dosomething.org/br)

![image](https://cloud.githubusercontent.com/assets/6330971/10256935/63f7c2ec-6922-11e5-92a9-8f6fa49ce96d.png)
- as user 2987614 (lang: BR PT) I'm seeing BR PT titles and BR PT CTAs on thor.dosomething.org/br before using the finder. this is correct

![image](https://cloud.githubusercontent.com/assets/6330971/10256906/2bcf2540-6922-11e5-93b6-9a686555aaa7.png)
- as user 2987614 (lang: BR PT) I'm seeing BR PT titles and BR PT CTAs in finder results onthor.dosomething.org/br. this is also correct

![image](https://cloud.githubusercontent.com/assets/6330971/10256948/78996944-6922-11e5-8adc-253b7fbef56f.png)

not sure how much of an issue this is because once #5349 is closed BR users shouldn't be able to hit this page.

moving to Global 1.1 because of this

cc: @mshmsh5000

**Comment by itsjoekent** [comment] 2015-10-29 13:46
I can't reproduce this issue anymore, I think it's because of all the new logic (eg: #5349) that's been implemented since this issue was made

can we close out?

**Comment by mshmsh5000** [comment] 2015-10-29 16:01
I agree @deadlybutter -- this is most likely outdated. @mikefantini, I suggest closing this out. We can re-open with fresh eyes if we can reproduce anything like it against the current codebase.

**Comment by mikefantini** [comment] 2015-10-29 16:03
Sounds good.

**Comment by mikefantini** [comment] 2015-11-16 16:55
This is happening again in the finder if:
- GL EN translation is published
- BR PT translation exists, but is unpublished

Go to thor as a user from BR and filter by cause "Meio ambiente"

![image](https://cloud.githubusercontent.com/assets/6330971/11188454/e75dda14-8c58-11e5-9dbe-b6a5a4dcdd89.png)

**Comment by mikefantini** [comment] 2015-11-16 17:01
To be clear, for Bookmark Climate Change, since GL EN is the published content that should be accessible for the user, we would want the Title and CTA to appear in GL EN.

**Comment by mikefantini** [comment] 2015-11-17 16:59
@blisteringherb I think when you fixed #5570 you resolved this issue as well:

![image](https://cloud.githubusercontent.com/assets/6330971/11218346/987ee670-8d22-11e5-9f19-f2bd6e7b1424.png)

**Comment by mikefantini** [comment] 2015-11-17 16:59
(see Bookmark Climate Change which was the offending campaign previously)

**Comment by blisteringherb** [comment] 2015-11-17 16:59
Yay!

**Closed as completed** 2015-11-17 17:02 UTC
Labels: bug, @bender, BLOCKER, #global, #translation
