### ISSUE TITLE
Fact: Test user access to Facts

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#427] opened 2014-01-21 20:07 UTC
Based on settings in dosomething_fact_permission(), dosomething_fact_access() should control access to Fact pages.

**Comment by aaronschachter** [comment] 2014-01-23 14:00
This may be related to #446 -- however, the 2nd param in `dosomething_fact_access()` is actually not an $account object, but an $entity object, per `entity_access()`.  Working on a PR to clean this up a little bit.

**Comment by aaronschachter** [comment] 2014-01-23 14:10
This issue is essentially a duplicate of #446.  Closing this one for now, as it seems to be affecting all features.  The changes in #429 are causing #441

**Closed as completed by aaronschachter** 2014-01-23 14:10 UTC
