### ISSUE TITLE
Global redirects are behaving erratically

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5920] opened 2015-12-08 18:02 UTC
#### Current Behavior

When I go to www.dososomething.org/stress I'm correctly redirected to www.dosomething.org/us/campaigns/less-stress-text and www.grandparentsgonewired.com I'm correctly redirected to www.dosomething.org/us/campaigns/grandparents-gone-wired-0. 

However, I have seen Adam have an inconsistent experience where sometimes he is redirected to the /us/ version correctly but sometimes it stays on www.dosomething.org/campaigns/less-stress-text or www.dosomething.org/campaigns/grandparents-gone-wired-0.

This results in the error "Global translation unavailable for."
#### Desired Behavior

The desired behavior is that users in the US are redirected to the US translation of these campaigns.
#### Steps to Replicate

Go to www.dosomething.org/stress or www.grandparentsgonewired.com and see the below error.
#### Why This Matters

All of our external marketing for these two campaigns are to these vanity URLs.
#### OS/Browser

OS X El Capitan, 10.11.1 (15B42)
Chrome: Version 47.0.2526.73 (64-bit)
Safari: Version 9.0.1 (11601.2.7.2)
#### Relevant Screenshots

![image](https://cloud.githubusercontent.com/assets/6330971/11663679/94de893c-9dab-11e5-88fb-c7e862e463a2.png)

**Comment by sergiitk** [comment] 2015-12-08 18:06
Hi! I think it's related to the origin country of the user accessing this short urls. I'm not getting redirected either.

**Comment by mikefantini** [comment] 2015-12-08 18:07
He is also not being redirected when he goes to www.dosomething.org/campaigns/grandparents-gone-wired-0 to the /us/ translation.

Also he is being sent to the GL EN homepage in Safari and Chrome when he goes to www.dosomething.org (instead of being taken to /us)

**Comment by sergiitk** [comment] 2015-12-08 18:08
cc @deadlybutter. Can you give it a look?

**Comment by itsjoekent** [comment] 2015-12-08 18:08
ok thats really weird

**Comment by itsjoekent** [comment] 2015-12-08 18:09
maybe dumb question -- should I check adams computer for anything funky? maybe some privacy setting or incorrect language is enabled?

**Comment by mikefantini** [comment] 2015-12-08 18:09
@deadlybutter give it a shot

**Comment by itsjoekent** [comment] 2015-12-08 18:17
found this on adams computer in the request headers

![image](https://cloud.githubusercontent.com/assets/897368/11664113/dc44f250-9dad-11e5-9c04-978c22348408.png)

shouldnt that be X-Fastly-Country-Code (not -Client) ??

Also it works ok on chrome, but not chrome incognito and safari

**Comment by itsjoekent** [comment] 2015-12-08 18:18
NOPE WAIT I FIGURED IT OUT SORTA KINDA.

Okay in the Request-Headers portion in the network inspect tab, there was nothing related to Fastly, the screenshot above is from the Response headers.

However on my computer (where it works) the Request Headers are present.

**Comment by mikefantini** [comment] 2015-12-08 18:19
@mshmsh5000 might this have anything to do with the Fastly updates that were made last night?

**Comment by mikefantini** [comment] 2015-12-08 18:21
Or @blisteringherb @sergii-tkachenko do either of you have any thoughts on this?

**Comment by sergiitk** [comment] 2015-12-08 18:25
@deadlybutter Do you have ModHeader enabled?

**Comment by itsjoekent** [comment] 2015-12-08 18:44
oh I do, and I just confirmed those variables are coming from mod header.

never mind!

**Comment by namimody** [comment] 2015-12-08 19:57
As a note, Marissa is also seeing the global homepage at dosomething.org and dosomething.org/stress is showing her the broken "global translation available for" page. cc @blisteringherb

**Comment by mshmsh5000** [comment] 2015-12-08 20:37
`X-Fastly-Country-Code-Client` is what's returned by Fastly in the browser response. If a user is not getting redirected, then you need to look at that header. If it's registering `US`, then the issue is probably with the app. If it's not registering `US`, then the issue is probably with Fastly.

**Comment by itsjoekent** [comment] 2015-12-08 20:38
hmmm interesting, thanks Matt!

**Comment by mshmsh5000** [comment] 2015-12-08 20:38
FWIW, I'm in Brooklyn on an LTE connection and am not getting redirected on the home page.

**Comment by sergiitk** [comment] 2015-12-08 20:39
I also tried to request homepage with US headers and hasn't been redirected to `/us/`.

**Comment by itsjoekent** [comment] 2015-12-08 20:40
works fine for me on laptop (chrome) and my mobile device (android, chrome)

**Comment by itsjoekent** [comment] 2015-12-08 20:51
| Name | Redirected Chrome | Redirected Chrome Incognito | Redirected Safari | Redirected Mobile |
| --- | --- | --- | --- | --- |
| Joe | Yes | No | No | Yes |
| Sergi | No? | No? | ? | ? |
| Matt LTE | Yes | Yes | Yes | No (Only for Safari, other browsers work) |
| Matt wifi | Yes | Yes | Yes | No (Only for Safari, other browsers work) |
| Adam | Yes | No | No | ? |
| Marissa | Yes | No | ? | ? |
| Fantini | Yes | Yes | Yes | Yes |

_please edit at will_

**Comment by mshmsh5000** [comment] 2015-12-08 21:04
The only place I've been able to reproduce the bug has been mobile Safari. I even tried another mobile browser, and the home page redirect to `/us` worked.

**Comment by itsjoekent** [comment] 2015-12-08 21:05
Gotcha, thanks!

**Comment by sergiitk** [comment] 2015-12-08 21:06
@deadlybutter Good table. Could clarify though, what url we should test and to what page we should be redirected?
www.grandparentsgonewired.com -> www.dosomething.org/us/campaigns/grandparents-gone-wired-0?

**Comment by mikefantini** [comment] 2015-12-08 21:06
Do we know if `X-Fastly-Country-Code-Client` is registering `US` or not per @mshmsh5000's comment?

https://github.com/DoSomething/phoenix/issues/5920#issuecomment-163010832

**Comment by mikefantini** [comment] 2015-12-08 21:07
@sergii-tkachenko I don't think you'd be redirected outside of the US, but yes that's the intended behavior for users in the US

**Comment by itsjoekent** [comment] 2015-12-08 21:09
@sergii-tkachenko wwww.dosomething.org 

im assuming you were testing via vpn

**Comment by itsjoekent** [comment] 2015-12-08 21:09
@mikefantini on Adams it was "US"

**Comment by itsjoekent** [comment] 2015-12-08 21:10
@mshmsh5000 I think I just overrided your previous edit with the LTE vs WIFI, ill fix sorry! (and dammit github!). someone tell github to make there comments use git

**Comment by DFurnes** [comment] 2015-12-08 21:11
Oh, interesting. This seems very similar to the [header issues we're having on the voting app](https://github.com/DoSomething/voting-app/issues/482). We saw similar wonkiness where incognito sessions on mobile browsers seemed to sporadically not send the country code header.

Sena sent a support request to Fastly, but I don't believe we've heard back yet.

**Comment by mikefantini** [comment] 2015-12-08 21:11
@deadlybutter also note though sometimes Adam is getting the error and sometimes he's having the desired behavior. i.e. in Safari he'll try and won't get redirect and and then he'll try again and he will get redirected. Although again, it will happen sporadically.

**Comment by mshmsh5000** [comment] 2015-12-08 21:12
The question with Adam is still whether his browser's receiving `X-Fastly-Country-Code-Client: US` when it's _not_ redirecting. We need to know that to narrow down the behavior.

**Comment by itsjoekent** [comment] 2015-12-08 21:13
@DFurnes maybe related? this is happening for people on wifi/desktop as well

also @mikefantini this is the error marissa had earlier.

clicked on the first DS Link here http://www.fastweb.com/content/fastweb-volunteers

and got brought to https://www.dosomething.org/about/easy-scholarships?utm_campaign=scholarships&utm_medium=link&utm_source=fastweb

(the global english page).

Ill re-check adams machine

**Comment by itsjoekent** [comment] 2015-12-08 21:30
checked his machine with fantini, in chrome incognito (not redirected) his request X_Fastly-Country-Client header was "US"

I know @mshmsh5000 said this was a bug earlier with the app, and it might be, but I'm not sure how to even debug a problem only a small fraction can reproduce?

also i pointed out earlier to fantini and Dave, in the error take a look at the actual message.

![image](https://cloud.githubusercontent.com/assets/897368/11669106/e78a25d4-9dc8-11e5-8c50-9b06f3351af8.png)

No translation available for <blank> . 

Is it trying to pull a null campaign?

**Comment by DFurnes** [comment] 2015-12-08 21:33
The placeholder for generating that string calls that a "label", so perhaps it's a missing label on an entity? If that's even a thing? (Keep in mind I have next to no idea about how Drupal works.)

```
html/profiles/dosomething/modules/contrib/entity_translation/entity_translation.module
984:  $message = t('%language translation unavailable for %label.', $args);
```

**Comment by mikefantini** [comment] 2015-12-08 21:50
Is there any way to know how often this message is occurring on prod?

**Comment by mikefantini** [comment] 2015-12-08 23:37
Updated the description because obviously this isn't just happening for vanity URLs.

**Comment by blisteringherb** [comment] 2015-12-09 17:19
Per Matt's comments in the meeting, let's look at things in this order:
1. Fastly inconsistency - Sena has reached out to them
2. Varnish redirect inconsistency
3. Session issues
4. Cached redirects in Varnish and Fastly (specifically look at anonymous 301s)

**Comment by mikefantini** [comment] 2015-12-09 17:19
For Fastly let's also look at logentries.com.

If Fastly is behaving consistently and Varnish config is correct, then we need to know what session behavior is in prod and how it may be affecting behavior.

We want only two classes of users:
- not logged in, no sessions
- logged in, with sessions

**Comment by mikefantini** [comment] 2015-12-09 18:17
FWIW neither Marissa nor Adam (who are seeing these issues on prod) can reproduce on thor.

**Comment by mikefantini** [comment] 2015-12-09 18:42
Update:

Adam is now able to produce three distinct experiences by going to www.dosomething.org/stress:
1. He gets redirected properly to the US translation https://www.dosomething.org/us/campaigns/less-stress-text
2. He gets redirected to a GL EN translation that does not exist https://www.dosomething.org/campaigns/less-stress-text and gets the following error
   ![image](https://cloud.githubusercontent.com/assets/6330971/11694903/8c2ebbfc-9e7a-11e5-9611-13bb9e0899ef.png)
3. He gets a redirect loop error and remains on www.dosomething.org/stress
   ![image](https://cloud.githubusercontent.com/assets/6330971/11694923/9fa3a724-9e7a-11e5-8d81-2009d71537d1.png)

**Comment by mikefantini** [comment] 2015-12-10 16:47
@mshmsh5000 @blisteringherb @deadlybutter any updates on this?

**Comment by itsjoekent** [comment] 2015-12-10 17:56
PR that removes session logic was merged yesterday, appears to have fixed https://github.com/DoSomething/phoenix/issues/5620

Nothing else related to the app layer

**Comment by mshmsh5000** [comment] 2015-12-10 19:28
With the fix for #5620 in production, I'm unable to reproduce this issue on Adam's machine, on any browser.

**Comment by blisteringherb** [comment] 2015-12-10 19:30
:+1:

**Comment by mshmsh5000** [comment] 2015-12-10 19:40
![6a0120a85dcdae970b0128776ff992970c-pi](https://cloud.githubusercontent.com/assets/149811/11726272/e4f253a8-9f4b-11e5-9095-6e04b42dff98.png)

**Comment by angaither** [comment] 2015-12-10 19:41
time for my fav 
![](http://cdn2.hubspot.net/hub/228391/file-745508197-jpg/blog-files/devopsevil.jpg)

**Comment by angaither** [comment] 2015-12-10 20:25
we are like 99% sure this is :ok: now

**Closed as completed by angaither** 2015-12-10 20:25 UTC
Labels: bug, priority-high, @devops, #global

**Comment by sergiitk** [comment] 2015-12-10 20:32
Wait, so it's actually fixed by #5928, right?

**Comment by itsjoekent** [comment] 2015-12-10 20:38
I think?

**Comment by sergiitk** [comment] 2015-12-10 20:41
:dancer:

**Comment by mikefantini** [comment] 2015-12-10 22:29
Currently as an admin when I go to www.dosomething.org/jobs I get taken to www.dosomething.org/about/were-hiring rather than www.dosomething.org/us/about/were-hiring.

And as an admin when I go to www.dosomething.org/stress I get taken to www.dosomething.org/campaigns/less-stress-text rather than www.dosomething.org/us/campaigns/less-stress-text.

I want to do a bit more digging into this before I reopen it.

**Comment by mikefantini** [comment] 2015-12-10 22:35
Here is the user: https://www.dosomething.org/us/user/329195/edit.

I'm able to replicate this for this user on:
- Chrome
- Chrome Incognito
- Safari
- Safari Private Window
- Safari mobile browser
- Firefox
- Firefox Private Window

It's working for me as an anonymous user on these browsers

**Comment by mikefantini** [comment] 2015-12-10 22:44
Also spot checking authenticated with my non-admin test account everything is working as anticipated.

It just seems to be that one admin user that I'm having issues with. Also with my admin user, when I go to www.dosomething.org I get redirected properly to www.dosomething.org/us. It just seems to be URL redirects like /jobs that seem to be giving me an error while I'm logged in as an admin.

Is anyone else seeing this with their admin user?

**Comment by itsjoekent** [comment] 2015-12-11 14:43
One of the original specifications for redirects was that admins were to be unaffected by the redirect logic (so they could access any page without interference).

Do you want to change this?

**Comment by mikefantini** [comment] 2015-12-11 14:47
Hmm ok. @deadlybutter I'm 99.99% sure I've been getting redirected as an admin this whole time, but this is definitely the more desired behavior. I just wanted to make sure that everyone else was seeing this behavior.

**Comment by itsjoekent** [comment] 2015-12-11 14:48
Yeah I'm not really sure why it decided to just start working

**Comment by mshmsh5000** [comment] 2015-12-11 14:55
I actually don't see the "user is admin" exception in the [init hook](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_global/dosomething_global.module#L16), but it is in the [node redirect function](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_global/dosomething_global.module#L592) for `302` responses.

So this should be avoiding redirects for node content for admin users, generally speaking, unless we specifically bypass this by issuing a `301`.
