### ISSUE TITLE
Vagrant: Coder module UI

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#294] opened 2013-12-20 17:06 UTC
Trying to run Coder Review on custom module results in:

Fatal error: Call to undefined method PHP_CodeSniffer::setTokenListeners() in /vagrant/html/profiles/dosomething/modules/contrib/coder/coder_review/includes/coder_review_sniffer.inc on line 88

**Comment by aaronschachter** [comment] 2014-01-10 14:35
You can still run `codercs` from the command line, as per https://github.com/DoSomething/dosomething/wiki/Contributing#coder, but it'd be great to get the Admin UI working, so we can enable and test against Coder Tough Love as well.

**Comment by deezone** [comment] 2014-01-22 14:12
Tried running "codercs" which produced:

vagrant@dev:/vagrant/modules/dosomething/dosomething_fact$ codercs dosomething_fact.module

ERROR: the "/profiles/dosomething/modules/contrib/coder/coder_sniffer/Drupal/ruleset.xml" coding standard is not installed. The installed coding standards are PEAR, MySource, PHPCS, Zend, Squiz, PSR1 and PSR2

Would you still call this a duplicate of #431 or a bigger problem? As detailed in #431, I was only able to get coder working through the drush command:

drush drupalcs YOURFILE

**Closed as completed** 2016-02-03 18:22 UTC
Labels: bug, @devops, NO
