### ISSUE TITLE
Featurecard not appearing when member is signed up for all staff picks 

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6877] opened 2016-08-15 16:51 UTC
#### Current Behavior

When a user is already signed up for all staff picks, the featurecard appears blank on onboarding. 
#### Desired Behavior

The user should see non-staffpick campaigns to sign up for. 
#### Steps to Replicate

1) sign in or create account
2) sign up for all staff pick campaigns
3) sign up for a campaign that isn't staff picked
4) observe
#### Why This Matters

We want to show all users the different campaigns that DS offers and encourage all to sign up for as many campaigns as they're interested in. 
#### Relevant Screenshots + Links

![screen shot 2016-08-15 at 12 51 22 pm](https://cloud.githubusercontent.com/assets/14931921/17671834/015a82cc-62e7-11e6-8dcc-1330fc65358d.png)

**Comment by angaither** [comment] 2016-08-16 14:03
isn't this a duplicate of #6818?

**Comment by jessleenyc** [comment] 2016-08-16 14:07
@angaither looks like i should have re-opened that ticket, yes.

**Comment by jessleenyc** [comment] 2016-08-16 17:19
@angaither should i close this and reopen the new one or can we leave as is?

**Closed as completed** 2016-08-17 15:18 UTC
Labels: #onboarding
