### ISSUE TITLE
Campaign: user should see "confirmation" page after reporting back

### ISSUE THREAD

**Issue by mmwtsn** [DoSomethingArchive/legacy-website#865] opened 2014-02-26 16:31 UTC
After reporting back on a campaign the node is reloaded. The user should see the confirmation page.

**Comment by barryclark** [comment] 2014-02-26 16:33
@aaronschachter would be great if you can take a look at this one today... then we'll have the full campaign flow working :rainbow:

**Comment by aaronschachter** [comment] 2014-02-26 16:33
Yeah, this should be in place.  Will definitely check it out.

**Comment by aaronschachter** [comment] 2014-02-26 16:53
Are you able to reportback ? I am blocked from being able to test a reportback by #419.  Perhaps what you're experiencing is the campaign reloading because when you click upload to upload file, the whole campaign reloads.  However, it's not reloading with the file anymore so you can't ever submit it.

**Comment by aaronschachter** [comment] 2014-02-26 16:55
You can confirm the reportback was submitted by viewing node/[nid]/reportbacks.  But my guess is that you're actually not able to submit.

**Comment by barryclark** [comment] 2014-02-26 16:55
cc @DFurnes ^^

**Comment by aaronschachter** [comment] 2014-02-26 17:05
@mmwtsn can you confirm that you actually aren't able to reportback?  if so this is a dup of #419

**Comment by aaronschachter** [comment] 2014-03-03 19:26
Closing, duplicate of #419

**Closed as completed by aaronschachter** 2014-03-03 19:26 UTC
Labels: bug, @bender
