### ISSUE TITLE
Campaigns endpoint returns all campaigns twice

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#4356] opened 2015-04-07 19:44 UTC
`/campaigns` returns sad double data

```
[
 {
  title: "Comeback Clothes",
  nid: 362,
  is_staff_pick: true
 },
 {
  title: "Comeback Clothes",
  nid: 362,
  is_staff_pick: true
 },
....
```

**Comment by aaronschachter** [comment] 2015-05-07 18:04
Duplicate of #4110. The endpoint currently is using the apache solr drupal view, about to look into #4110 now

**Closed as completed by aaronschachter** 2015-05-07 18:04 UTC
Labels: bug, #api
