### ISSUE TITLE
campaign_language in Campaign Signup and Reportback Transactions

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#5685] opened 2015-11-02 20:46 UTC
When a user signs up (`campaign_signup`) for a campaign or reports back (`campaign_reportback`) a request for a transactional message is sent to the Message Broker system. The payload of the message request needs to include the `campaign_language`. The value comes from the language setting for the related campaign node.

**NOTE**: This is different than the `user_language` and `user_country` which are currently in the request payload but does not address this issue.

**Example payload**:

```
(
    [activity] => campaign_signup
    [email] => mfantini+pttranslator@dosomething.org
    [uid] => 3202400
    [campaign_language] => en-global
    [merge_vars] => Array
        (
            [MEMBER_COUNT] => 4.3 million
            [FNAME] => Brazil
            [CAMPAIGN_TITLE] => Sea Turtle Street Sweep
            [CAMPAIGN_LINK] => https://thor.dosomething.org/us/campaigns/sea-turtle-street-sweep?source=node/3624
            [CALL_TO_ACTION] => Save sea turtles by picking up trash before it reaches the ocean.
            [STEP_ONE] => Clean Up Trash!
            [STEP_TWO] => Snap a Pic
            [STEP_THREE] => Haul It Away
        )

    [user_country] => US
    [user_language] => en
    [email_template] => mb-campaign-signup-US
    [subscribed] => 1
    [event_id] => 3624
    [email_tags] => Array
        (
            [0] => 3624
            [1] => drupal_campaign_signup
        )

    [activity_timestamp] => 1446224947
    [application_id] => US
)
```

**Related Issues**:
- https://github.com/DoSomething/phoenix/issues/5601
- https://github.com/DoSomething/phoenix/issues/5804

**Comment by mikefantini** [comment] 2015-11-17 15:34
@DeeZone @blisteringherb do you have an update on this?

Just tested on thor and received an email in Portuguese for a campaign that is in GL EN as a Brazilian user:

![image](https://cloud.githubusercontent.com/assets/6330971/11215954/b422f59e-8d16-11e5-8e30-2702b88835a2.png)

cc: @marahml

**Comment by deezone** [comment] 2015-11-17 21:33
@mikefantini @blisteringherb 

Still a "BLOCKER". I'll take a look and give a status report. The key is getting the campaign language into the request to Message Broker. In terms of campaign signups this should not be difficult. Report backs might be harder as the "reportback object" does not currently contain the campaign language.

I'll make additional issues as / if needed.

**Comment by marahml** [comment] 2015-11-19 19:57
Hey @sergii-tkachenko! @DeeZone tackled the signup email portion of this issue. For onboarding + debugging, are you able to tackle the reportback email? cc @sheyd

**Comment by sergiitk** [comment] 2015-11-19 19:58
Yes!

**Comment by angaither** [comment] 2015-11-19 20:03
refs #5803
maybe even duplicate of?

**Comment by marahml** [comment] 2015-11-19 20:07
Awesome - thanks @sergii-tkachenko!

**Closed as completed** 2015-12-02 15:57 UTC
Labels: #message-broker, #global, email-digest
