### ISSUE TITLE
Automated coder review upon pull request

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#63] opened 2013-10-18 13:35 UTC
If possible, it'd be great to get Coder Tough Love (yep) to run on all dosomething modules and themes upon pull request, to spare ourselves from reviewing things like spacing, comments, etc, and automatically reject a pull request if it fails.

Will ensure good commenting and good looking code.

**Comment by mchitten** [comment] 2013-11-13 19:10
Accidental duplicate of #146.  One day we may want to consider abstracting our review script to do whatever we want (e.g. js linting, other linting?), but that's for another day.

**Closed as completed by mchitten** 2013-11-13 19:10 UTC
