### ISSUE TITLE
Multiple Campaigns Runs Were Created

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#6064] opened 2016-01-20 00:35 UTC
#### Current Behavior

Multiple runs were created for some campaigns in  #5961. See https://www.dosomething.org/admin/content/search?title=senior+socials&type=campaign_run&field_cause_tid=All&status=All&language=All as an example. Note Senior Socials the campaign only exists in US English, so this doesn't appear to be a translation issue.

This doesn't seem to have occurred on thor, only production.
#### Desired Behavior

Only one run 1 should exist for each campaign.
#### Steps to Replicate

If you go to https://www.dosomething.org/admin/content?sort=asc&order=Title and filter by type = campaign run you can see all the instances in which multiple runs were created.
#### Why This Matters

Part of the goal of this runs effort was to clean up the data, and having dummy runs associated with campaigns will likely confuse admins in the future.

cc: @angaither 

Also note, in trying to resolve a potentially related issue I tried associating duplicate runs for Quitters Always Win (nid 10) with a dummy campaign. However I did not change those back as these duplicate runs should really be deleted anyways.

**Comment by chloealee** [comment] 2016-01-20 14:06
Thanks, Mike! 

@angaither since #5961 was only meant to run once (versus a script we use over and over), I'm thinking the best way to approach this is to make another function in the `dosomething_campaign_run.install` file to query for all the duplicate runs for a campaign and delete all but one. Let me know if this is the correct path to go down and I'll get on it!

**Comment by angaither** [comment] 2016-01-20 16:14
@chloealee no, this did not happen on thor, and the same code ran it doesn't make sense on why it would work differently on production. 

cc @sheyd @blisteringherb 
is there any reason you can see why this would happen?

query that ran on thor & prod

```
SELECT t.entity_id, group_concat(t.created) as created_dates, n.language as src_lang, group_concat(t.language) as languages, d.title_field_value
                                FROM entity_translation t
                                INNER JOIN field_data_field_campaign_status s on s.entity_id = t.entity_id
                                INNER JOIN node n on n.nid = t.entity_id
                                INNER JOIN field_data_title_field d on d.entity_id = t.entity_id and t.language = d.language
                                WHERE field_campaign_status_value = 'active'
                                GROUP BY t.entity_id;
```

it produces the same results in both environments. 
for each row returned, it creates a campaign run node. 
for node id = 10, one row is returned, so one campaign run should have been created. 
this worked correctly on thor, but in prod it produced 3 run nodes. 

take a look at here to have a closer look at what is going on in the code https://github.com/DoSomething/phoenix/pull/6037/files

**Comment by sheyd** [comment] 2016-01-20 20:32
@chloealee @angaither For clarification, is this the order of operations that happened to get us to this state:
- Prod Snapshot to Thor
- Deploy Campaign Run Test Code (v 2.??)
- Test run of `dosomething_campaign_run.install` code to create campaign runs on Thor
- Thor has 1 campaign as tested via query
- Deploy to Prod
- Prod has 3 campaigns instead.

**Comment by angaither** [comment] 2016-01-20 20:37
@sheyd correct and it looks like it was v2.1.19

**Comment by sheyd** [comment] 2016-01-20 20:39
@angaither Thanks for version! Backtracking to see what could have caused this.

**Comment by sheyd** [comment] 2016-01-21 15:56
@angaither @mikefantini This was caused by an issue in our deployment process where `updb` ran multiple times (Sergii is testing a fix for this now). The number of campaigns that have multiple run creations I don't currently know. 

Next steps:
1. Track down all campaigns with multiple runs
2. Have someone strip them out via script?

Sound like a good course ^^ @angaither @mikefantini ?

**Comment by mikefantini** [comment] 2016-01-21 16:27
@sheyd that course of action makes sense to me.

**Comment by angaither** [comment] 2016-01-21 16:51
It might be easier to just manually delete them. 
duplicates can be easily seen with this query 

```
SELECT t.entity_id as runnid, r.field_current_run_target_id as active_run, group_concat(d.title_field_value) as titles, concat('dosomething.org/node/', t.entity_id, '/delete') as link
FROM entity_translation t
INNER JOIN node n on n.nid = t.entity_id
INNER JOIN field_data_title_field d on d.entity_id = t.entity_id and t.language = d.language
inner join field_data_field_campaigns c on t.entity_id = c.entity_id
inner join field_data_field_current_run r ON c.field_campaigns_target_id = r.entity_id
WHERE d.title_field_value LIKE '%run 1'
GROUP BY t.entity_id
ORDER BY titles;
```

**Comment by chloealee** [comment] 2016-01-21 18:08
thanks, @angaither! I'll hop on this and finish the above. 

@sheyd when you get a chance, would you mind helping me get the prod database set up?

**Comment by angaither** [comment] 2016-01-22 16:05
@mikefantini closing, I removed the duplicates. 
there's some that _appear_ to still be duplicates, but it's because the actual campaign node has a bunch of duplicates

**Closed as completed by angaither** 2016-01-22 16:05 UTC
Labels: bug, #campaign-runs
