### ISSUE TITLE
illegal choice detected on inbox occurring with inbox >25

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5023] opened 2015-09-03 21:57 UTC
which contradicts the summary [here](https://github.com/DoSomething/phoenix/pull/4858#issuecomment-132351644)

the offending nid: 2805

![image](https://cloud.githubusercontent.com/assets/6330971/9672024/193d84cc-5265-11e5-9ece-523958ecc59a.png)

cc: @weerd @deadlybutter

**Comment by namimody** [comment] 2015-09-14 14:46
HI @mikefantini -- Micah reported that Indonesia encountered this problem (see screenshot below). I'm not too familiar with this bug, but "Approved" is not pre-selected on their site, and it seems like the campaign in the screenshot doesn't have any RBs in the inbox -- so I'm not sure if their selections went through or the bug pushed unreviewed RBs to reviewed. They have a big partnership coming up with an Indonesian magazine -- what's the latest on this and what can we do for them?

![image](https://cloud.githubusercontent.com/assets/12396076/9852534/d17a2454-5acc-11e5-929d-3d9b1e689767.png)

**Comment by namimody** [comment] 2015-09-14 14:47
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;6B4PVTok&#x2F;1479-ds-indonesia-can-t-approve-report-backs"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> DS Indonesia can&#39;t approve report backs</a>

**Comment by namimody** [comment] 2015-10-05 19:46
Notes from Shawn: reviewed 25, took long time to submit, got this screen,
![image](https://cloud.githubusercontent.com/assets/12396076/10291234/caac6dc0-6b76-11e5-9cab-bcf68526ab13.png)

did another 25, took long time to submit, got this screen again,
![image](https://cloud.githubusercontent.com/assets/12396076/10291436/c7351cfe-6b77-11e5-9d97-63a3c78e2efb.png)

clicked back to page with all RBs reviewed and radial buttons were clicked, checked all were reviewed, submitted, got: 

![image](https://cloud.githubusercontent.com/assets/12396076/10291508/2df633ba-6b78-11e5-9033-f429c47b0266.png)

but it seems that review choices were saved and the RBs were marked as reviewed.

**Comment by mikefantini** [comment] 2015-10-05 19:49
let's break out the "No data received" into a separate issue and assign that one to @sheyd.

assigning this issue to myself right now

**Comment by mikefantini** [comment] 2015-10-06 17:35
i'll keep taking a look, but assigning over to @weerd since he has wrapped up all Global 1.0 work that was assigned to him

**Comment by mikefantini** [comment] 2015-10-06 22:01
related slack conversation https://dosomething.slack.com/archives/campaign-template/p1444160549000091

i think this issue may be related to #5112

**Comment by weerd** [comment] 2015-10-08 19:01
#### Reportback Review: Illegal Choice Bug

If you submit the RB review form and **any** items in the list have not been reviewed then it will throw the `illegal choice error`.

If RB review inbox is full with over 50 items (so 25 showing, 25 in next round), Editor reviews first 25 and if Member submits new RB before Editor hits submit on the reviewed items then all is fine. Works great cause there's an additional 25 in the queue and just submitted Member RB gets added to queue (so there's another 25, and it would be added as the 26th on next page).

If RB review inbox is full with over 25 items (so 25 showing and 1 on next round), Editor reviews first 25 and if Member submits new RB before Editor hits submit on the reviewed items then all is fine. Works great cause just submitted Member RB gets added to queue.

If RB review inbox is **not** full (less than 25 items), Editor reviews the items and if Member submits new RB before Editor hits submit on the reviewed items, then we get the `illegal choice error`, returns you to the inbox and all item statuses (stati?) for prior items is checked, new item statuses are unchecked.

---

It's very possible we're seeing this occurring because the minimum threshold of 25 items in Inbox view is not met and Members are submitting Reportbacks while these (less than 25) items are being reviewed.

**Comment by weerd** [comment] 2015-10-08 19:29
Assigning back to you @mikefantini until there are further developments...

**Comment by namimody** [comment] 2015-11-02 22:28
Helpful vid from a campaigns' intern reviewing RBs housed in Slack here: https://dosomething.slack.com/archives/phoenix/p1446503223001452

**Comment by mikefantini** [comment] 2015-12-04 22:58
@namimody have we heard instances of this recently?

**Comment by namimody** [comment] 2015-12-11 00:24
@mikefantini not since the 2nd when i posted the video -- and Adam just confirmed that he hasn't heard about/seen it in a while. added to the tech/campaigns sync agenda for next week, so we can confirm then. closing for now.

**Closed as completed by namimody** 2015-12-11 00:24 UTC
Labels: bug, #campaign-reportback-admin
