### ISSUE TITLE
Flagged RBs Show NULL and 0 Statuses

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4829] opened 2015-08-11 22:36 UTC
```
select rb.rbid, rbf.fid, rb.flagged, rb.promoted, rbf.status, from_unixtime(rb.created), from_unixtime(rbf.reviewed) as reviewed
from dosomething_reportback rb
inner join dosomething_reportback_file rbf on rb.rbid = rbf.rbid
and rbf.status = 'flagged'
and (rb.flagged is null or rb.flagged = 0)
order by reviewed desc;
```

![image](https://cloud.githubusercontent.com/assets/12396076/9212464/046cb4c0-4057-11e5-9e9b-be07113cb397.png)

92113 - reviewed 10:55:54 on 8/11 as flagged, status shows up as 0 instead of 1
92140 - reviewed 10:55:54 on 8/11 as flagged, status shows up as NULL instead of 1

Code deployed for this at 16:33 on 8/3:
![image](https://cloud.githubusercontent.com/assets/12396076/9212520/944e34ba-4057-11e5-8cc1-96e8b520a864.png)

(98019 and 98022 reflect a separate known issue.)

**Comment by namimody** [comment] 2015-08-12 23:20
Another instance -- pulled 8.12.15 at 7:20 PM on Visionary Volunteer. See 92139

![image](https://cloud.githubusercontent.com/assets/12396076/9239169/2bcbdfd4-4127-11e5-86a1-0d5861525f98.png)

**Comment by namimody** [comment] 2015-08-17 14:53
Another instance - Get Lucky pulled 8.17 around 10 AM. See RB 99004 and 99282. note this is from the slave database.
![image](https://cloud.githubusercontent.com/assets/12396076/9307728/1e6cf77e-44ce-11e5-94cb-e098c9e2437d.png)

**Comment by namimody** [comment] 2015-08-17 20:54
Get Lucky, pulled @ 4:50 pm 8.17

![image](https://cloud.githubusercontent.com/assets/12396076/9316022/a782163e-4500-11e5-8606-b006e1e412e5.png)

**Comment by namimody** [comment] 2015-08-17 21:01
Storm Drain Street Art, pulled 4:57 PM, 8.17. RB 99147 flagged and excluded but marked as NULL.
![image](https://cloud.githubusercontent.com/assets/12396076/9316203/a82d55ca-4501-11e5-9aca-a903e16949a3.png)

**Comment by angaither** [comment] 2015-08-18 18:44
@namimody @mikefantini have you been able to replicate this or #4829 on stage?

**Comment by weerd** [comment] 2015-08-18 20:56
So on my local with an inbox full of unreviewed RBitems for campaign 1247, I went through and for each item I selected each possible option (started with flagging and giving it a reason, so 4 of them; then promoted and giving a reason, so 4 of those too; then excluded and then the rest left as approved) and submitted the form:

![image](https://cloud.githubusercontent.com/assets/105849/9342355/2d7c60dc-45c9-11e5-940a-01924643d26a.png)

Mostly everything resulted as expected on the **dosomething_reportback** table, except that the one item I indicated to delete (`rbid: 1357`) was not actually deleted and the item marked as excluded (`rbid: 1362`) looks like any of the other approved ones.

The **dosomething_reportback_file** table shows that everything looks like it should:

![image](https://cloud.githubusercontent.com/assets/105849/9342623/e4555e16-45ca-11e5-80ae-1edc29e4a5b0.png)

Alhtough again, `rbid: 1357; fid: 3050` has not been deleted.

**Comment by weerd** [comment] 2015-08-18 21:20
Here's a more concise view over the series of RB items I reviewed:

![image](https://cloud.githubusercontent.com/assets/105849/9343023/4be037ca-45cd-11e5-9eac-69165f5e89df.png)

Again, the only odd one is the one that should have technically been deleted (the highlighted one, `rbid: 1375`)...

**Comment by mikefantini** [comment] 2015-08-19 21:46
Findings:
- happening on master/prod db starting 2015-08-06 20:48:09 (reviewed timestamp) with RBID 92253 FID 125123
- happening on slave/prod db starting 2015-08-06 16:48:09 (reviewed timestamp) with RBID 92253 FID 125123
- no instances of this happening on staging db

@angaither did you write any scripts or updates that would have run that would have cleaned up pre-existing data without the issue itself actually being resolved? took a quick peak but couldn't find anything

**Comment by mikefantini** [comment] 2015-08-19 21:53
i feel like there has to have been an update because we saw this happening on staging db and on master/prod db in #4529 in May/June

**Comment by angaither** [comment] 2015-08-20 14:25
@mikefantini we have a cron that runs to update reportbacks #4719

**Comment by angaither** [comment] 2015-08-20 14:27
There's also an update hook to clean up stuff that was run on deploy in release v1.0.28 #4814

**Comment by angaither** [comment] 2015-08-24 19:16
refs #4887

**Comment by angaither** [comment] 2015-08-24 19:27
@namimody have we been seeing this or #4815 since we added the correct permissions to editors/site admins?

**Comment by angaither** [comment] 2015-08-26 16:22
I think we are good to close this issue out, I've confirmed after the script + editor/member support permissions were added we are no longer seeing this

**Closed as completed by angaither** 2015-08-26 16:22 UTC
Labels: bug, #campaign-reportback-admin
