### ISSUE TITLE
Clean Slate command in Admin does not update the reportback count

### ISSUE THREAD

**Issue by weerd** [DoSomethingArchive/legacy-website#4252] opened 2015-03-19 18:22 UTC
When using the Admin command to **Clean Slate** for a campaign (or user?), the reportback count for a campaign does not update properly and still refers to the old count, which will throw off visual/code testing of reportback gallery ending up with a seemingly empty reportback gallery:

![image](https://cloud.githubusercontent.com/assets/105849/6737632/39a6d8c2-ce43-11e4-9758-a3ce8853f458.png)

Need to update the command to re-query the db after clearing the data and set the proper reportback count for the campaign.

@aaronschachter @mikefantini

**Comment by mikefantini** [comment] 2015-03-20 18:53
making this a low priority because this will only ever occur on staging.

**Comment by angaither** [comment] 2015-12-04 22:51
closing duplicate of #4849

**Closed as completed by angaither** 2015-12-04 22:51 UTC
Labels: bug, @bender, priority-low, #campaign-template
