### ISSUE TITLE
Logins do not persist across domains

### ISSUE THREAD

**Issue by angaither** [DoSomethingArchive/legacy-website#1509] opened 2014-03-25 14:30 UTC
If you login to beta.ds.org the you do not appear to be logged in to www.ds.org

**Comment by mikefantini** [comment] 2014-03-25 16:37
confirmed. only a problem if jumping from beta. www. or legacy.

not an issue if you're just using www. the whole time (so only an internal issue)

i.e. 
if you're logged out of beta. legacy. and www., go to www.ds.org/causes, log in, and go back to www.ds.org/causes you're still logged in.

then if you go to www.ds.org/campaigns (on the new app) you're still logged in.

it's only when you try to then go to beta.ds.org/campaigns that you are no longer logged in

**Comment by angaither** [comment] 2014-03-25 18:09
Thinking #1494 PR is what borked logins across beta.ds/legacy.ds/www.ds

**Comment by aaronschachter** [comment] 2014-07-03 00:25
This one's been open for a while, and doesn't seem to have caused too much pain, since it's really only an internal issue.  Since we're getting way close to completely ditching the live legacy site, I think it's fine to close this one out too.

**Closed as completed by aaronschachter** 2014-07-03 00:25 UTC
Labels: bug, @bender, @devops
