### ISSUE TITLE
Remove "User Profile Link" theme setting / conditionals 

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#3260] opened 2014-10-28 12:22 UTC
Cleanup task for once we're ready to go live with the Profile. We don't need the theme setting or the conditional logic in the template anymore.

**Comment by mikefantini** [comment] 2014-11-11 16:00
@aaronschachter is this duplicate of #1861 or just related?

**Comment by aaronschachter** [comment] 2014-11-11 16:03
It is related, not a duplicate. #1861 is for theming, this is to remove the code that's checking for a theme setting for whether or not display the Profille (and to just always display)

**Comment by itsjoekent** [comment] 2015-02-17 15:31
That PR did not fix this, description was outdated

**Closed as completed** 2015-02-18 21:35 UTC
Labels: @fender, #user-profile
