### ISSUE TITLE
[User Profile] Update top nav to link to profile

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#1861] opened 2014-04-18 16:35 UTC
![screen shot 2014-04-18 at 12 31 55 pm](https://cloud.githubusercontent.com/assets/6550604/2743651/6a8ff9b6-c717-11e3-9932-779990feac38.png)

@julielorch heads up this is a visualization for what we mentioned in the kick off meeting.

**Comment by weerd** [comment] 2014-05-07 21:07
This is all set, but there may be some input regarding the pipe and whatnot. @crystalruthbell please chat w/ @mikefantini regarding the feedback and lemme know what to change! :dancer:

**Comment by joolaay** [comment] 2014-05-07 21:13
holla, we had a quick chat w/ nancy + need to hold on this for a bit...

Having a quiet profile launch & some testing,  with Nav edits coming later. Pipe is a no-go :(

**Comment by aaronschachter** [comment] 2014-11-10 17:13
@julielorch @lkpttn Is this issue still valid?  The new mocks show a pipe character.

**Comment by mikefantini** [comment] 2014-11-11 15:34
yes this is still a valid issue

**Comment by joolaay** [comment] 2014-11-11 15:36
@mikefantini and I chatted yesterday - I don't remember this being approved but he says we're good to go

**Comment by mikefantini** [comment] 2014-12-22 21:13
@aaronschachter i assume you closed this because it's a duplicate of #3260?

**Comment by aaronschachter** [comment] 2015-01-14 15:30
Not sure what needs to happen here, but this is one of the last issues to close out this milestone.

**Comment by lkpttn** [comment] 2015-01-14 17:22
[This mock](https://a0465d35-a-5d563b7e-s-sites.googlegroups.com/a/dosomething.org/dosomethinguxwiki/home/product-archive/profile-template/Desktop%20Full.jpg?attachauth=ANoY7cprkFhQYFKwmiEHpHwxzhzcsBvtgOg18fB3kYAmLjRNJK4KDWfu38DE0RjUvKcbgdXM7t0uaiVTryqQqAxK-NcdValzWNfOG-KWxDSmorHitentJYrxfd0HhfEIS-2isuMzRFIuKGxZuGxPud5btiLDZksZiJVxgyvRsPJNWv37UPLoxG_xmrs5_-e0ueh7-c4gEFuAcZBy_MKVTkNPbszfojzp_-AWG2OmXlkgUY6yyOFDgBdA2MrbI806XFD4SAbm_zYY28CChLTAC8qmlMBeGnj6GA%3D%3D&attredirects=0) is still accurate, first name + pipe character.

**Comment by aaronschachter** [comment] 2015-01-14 18:58
Ok i've turned this on on staging to give more clarity.  There is no pipe after the username, so we need that.  The pipe spacing is also funky when the user is logged out.

What should the text read when the user is logged out?  "Create an account"? "Register" ? @lkpttn @mikefantini

**Comment by mikefantini** [comment] 2015-01-14 19:00
@aaronschachter @deadlybutter I'd vote for "Create an account" as long as the longer text doesn't mess with responsiveness

**Comment by lkpttn** [comment] 2015-01-22 15:39
We have a new solution for the crowded header:

![unclicked](https://cloud.githubusercontent.com/assets/1865372/5858651/da67a662-a222-11e4-8bdc-895fe15acc6d.png)

![clicked](https://cloud.githubusercontent.com/assets/1865372/5858656/ddea8dcc-a222-11e4-8691-2a858ec1f3d5.png)

And mobile

![mobile](https://cloud.githubusercontent.com/assets/1865372/5858661/e3551af2-a222-11e4-82ae-6fb332e18344.png)

**Closed as completed** 2015-02-17 15:30 UTC
Labels: @fender, #user-profile
