### ISSUE TITLE
Campaign form: Primary Cause, Issue autocheck 

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#578] opened 2014-02-04 00:00 UTC
These should auto-select the appropriate taxonomy in the appropriate multi-select list.

i.e. if I select Animals as my Primary Cause, Animals should be automatically selected under the Cause multi-select list.

![image](https://f.cloud.github.com/assets/6330971/2071814/430fc14a-8d2f-11e3-891d-7f16e3a27976.png)

**Comment by barryclark** [comment] 2014-02-04 21:15
@mikefantini Is the idea for this that whenever someone selects a Primary Cause menu item, the corresponding Cause checkbox gets checked?

**Comment by mikefantini** [comment] 2014-02-04 21:17
@barryclark exactly. same for primary action type

**Comment by barryclark** [comment] 2014-02-04 21:24
Discussed this with Fantini and this Issue is low priority so we're going to bump it to Milestone 0.3.0. We'll assign it and get this knocked out when a lot of the high priority work is taken care of.

**Comment by barryclark** [comment] 2014-06-24 20:33
I really want to close this as I feel like the technical effort would be too high for such a tiny amount of value. 

@aaronschachter You implemented the Javascript on the SMS Template switcher. Is there a straightforward (5 minute) way to do this?

cc @weerd

**Comment by aaronschachter** [comment] 2014-06-24 21:05
Actually it really shouldnt be that bad, but there's gotchas that would make it worse than 5 mins. e.g. If a user wants to be a wise guy and unchecks the Cause field that was auto-checked.

**Comment by barryclark** [comment] 2014-06-24 21:54
@mikefantini Closing this one as it's going to take more technical effort to complete than the value we'll get out of it.

**Closed as completed by barryclark** 2014-06-24 21:54 UTC
Labels: @fender
