### ISSUE TITLE
action page (report back modal) - styling needed

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1125] opened 2014-03-11 01:30 UTC
- [Annotated mocks](https://a0465d35-a-5d563b7e-s-sites.googlegroups.com/a/dosomething.org/dosomethinguxwiki/home/product-archive/campaign-template/Report%20Back%20Modals%20-%20Annotated%20Mocks.png?attachauth=ANoY7copRVYQ4JrAOP1X5yI7BPWWKJw2en2dBGyNzX8226H3BlWdbW_SepVvqe1Ycu41wL-fgz0Lmqon_C4rKXVYCPYiFR_IkwCOve7OGt81fWw-akL5KDacUEtrjHMHIcWHemlc7TQI4xTZ4uk210wwG6scLTFKtHDGe_i-80nI2A5-2FYgciwfG7rc3agHLfmdoHYGuhArT6vd6pITu0ol5auya_RHoKgPt45r1ACNtmbRdc3z4Bw1QvnBK0fW70O7UfxT9yLd8vvw5sBCFJUJtcJjfjAAPuUbV6Fh9ZFs2HUSNaPMc__ulMedbs1lXWlDV1C9eFvh&attredirects=0)
- [PSD of empy fields](https://sites.google.com/a/dosomething.org/dosomethinguxwiki/home/product-archive/campaign-template/keri_modals_mob_preentry.psd?attredirects=0&d=1)
- [PSD of completed fields](https://sites.google.com/a/dosomething.org/dosomethinguxwiki/home/product-archive/campaign-template/keri_modals_mob_postentry.psd?attredirects=0&d=1)

Currently:
![image](https://f.cloud.github.com/assets/6330971/2381118/2601ccb8-a8bb-11e3-9aa1-fd866eb5a553.png)

**Comment by DFurnes** [comment] 2014-03-11 20:29
Duplicate of #1015.

**Closed as completed by DFurnes** 2014-03-11 20:29 UTC
Labels: @fender
