### ISSUE TITLE
campaign finder unresponsive in thor

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5204] opened 2015-09-23 17:27 UTC
working for me on staging and prod

**Comment by blisteringherb** [comment] 2015-09-23 19:50
I'm not able to reproduce this. Was the finder unresponsive as an anonymous user or logged in? What's the user's language?

**Comment by mikefantini** [comment] 2015-09-23 20:13
anonymous user @blisteringherb

**Comment by mikefantini** [comment] 2015-09-23 20:14
also happening for me logged in as a BR admin and logged in as an administrator

**Comment by mikefantini** [comment] 2015-09-23 20:15
![image](https://cloud.githubusercontent.com/assets/6330971/10057444/55c18eee-620e-11e5-8fa2-48cd7f5c3a38.png)

**Comment by blisteringherb** [comment] 2015-09-23 21:19
moved this comment to #5217

---

I'm seeing this for an anonymous user, but I can't replicate the behavior above. The issues I'm seeing are related to the fact that there are no en-global translated campaigns for several of the tags. If we switch the default language to 'en-global' it will break the finder, because the initial loading of the finder doesn't make any calls (from what I can tell) to Solr to find out what filters should be disabled. 

@DFurnes I feel like that can't be correct, do you remember how the finder initially hides the tags before the user has interacted with the filter?

Here's what I'm seeing
![screen shot 2015-09-23 at 4 35 47 pm](https://cloud.githubusercontent.com/assets/28132/10058027/328cd944-6211-11e5-881d-822cf2411511.png)

**Comment by mikefantini** [comment] 2015-09-23 21:42
@blisteringherb hmmm I don't totally understand why not having Global-En translations would be an issue since we're located in the US (so wouldn't anonymous see US-English content?) and since I'm seeing the same behavior as a MX Admin.

this is the error that i'm getting when trying to use the finder:

![image](https://cloud.githubusercontent.com/assets/6330971/10059623/17027720-621a-11e5-9ce5-7d6c92d6431a.png)

**Comment by mikefantini** [comment] 2015-09-23 21:46
from @mshmsh5000 "If it resolves for you, @blisteringherb, then this is a missing DNS entry from doserver2."

**Comment by mshmsh5000** [comment] 2015-09-24 01:10
[This request to Thor Solr](https://search-thor.dosomething.org/solr/collection1/select?fq=-sm_field_campaign_status:%28closed%29%20bundle:[campaign%20TO%20campaign_group]%20ss_language:%28en-global%20OR%20en-global%29&wt=json&indent=false&facet=true&facet.field=fs_field_active_hours&facet.field=im_field_cause&facet.field=im_field_action_type&rows=8&fl=label,tid,im_vid_1,sm_vid_Action_Type,tm_vid_1_names,im_field_cause,im_vid_2,sm_vid_Cause,tm_vid_2_names,im_field_tags,im_vid_5,sm_vid_Tags,tm_vid_5_names,fs_field_active_hours,sm_field_call_to_action,bs_field_staff_pick,ss_field_search_image_400x400,ss_field_search_image_720x720,url,ss_language&bq=ss_language:en-global^10&facet.query=im_field_cause:16&facet.query=im_field_cause:%2813%20OR%2017%29&facet.query=im_field_cause:12&facet.query=im_field_cause:14&facet.query=im_field_cause:2&facet.query=im_field_cause:4&facet.query=im_field_cause:%2819%20OR%205%29&facet.query=im_field_cause:%286%20OR%2015%29&facet.query=im_field_cause:%281%20OR%2021%29&facet.query=fs_field_active_hours:[*%20TO%201]&facet.query=fs_field_active_hours:[2%20TO%205]&facet.query=fs_field_active_hours:[6%20TO%20*]&facet.query=im_field_action_type:7&facet.query=im_field_action_type:3&facet.query=im_field_action_type:11&facet.query=im_field_action_type:8&facet.query=im_field_action_type:9&facet.query=im_field_action_type:18&facet.query=im_field_action_type:10&facet.query=im_field_action_type:20&start=0&_query_:%22{!func}scale%28is_bubble_factor,0,100%29%22%20AND%20&json.wrf=solrResponse) resolves from outside the office.

**Comment by blisteringherb** [comment] 2015-09-24 01:11
@mshmsh5000 I added it earlier today to Akamai. I forgot that I'd added it in my /etc/hosts but neglected to add it on dososerver2.

**Comment by blisteringherb** [comment] 2015-09-24 02:35
It should now also be resolving in the office as well.

**Closed as completed** 2015-09-24 14:12 UTC
Labels: bug, #campaign-finder, #global
