### ISSUE TITLE
campaign (pitch) - error message signing up for campaigns as a logged in user

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1262] opened 2014-03-14 15:32 UTC
I can't replicate but Alyssa was seeing this error:

https://trello-attachments.s3.amazonaws.com/52ea92c7ccdaf8415b8cab3a/53223bff3088366f7957dad7/1317x413/3dcf73a6212727bd8759eb74a21467a0/error1.JPG

She replicated a few times inconsistently by:
- being a logged in user 
- on a campaign pitch page
- clicking sign up button for that campaign

**Comment by aaronschachter** [comment] 2014-03-14 15:33
There was some wack code on staging for a minute yesterday thanks to me.  Was fixed by #1247

**Closed as completed by aaronschachter** 2014-03-14 15:33 UTC
Labels: bug

**Comment by aaronschachter** [comment] 2014-03-14 15:35
Duplicate of #1246
