### ISSUE TITLE
Image Tags Sporadically Disappear from Image Upload Page

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6139] opened 2016-02-04 19:57 UTC
#### Current Behavior

Currently there are checkboxes next to nonexistent image tags on the "image upload" page.
#### Desired Behavior

There should be text next to each checkbox on the image upload page.
#### Steps to Replicate
1. Go to a campaign page.
2. go to the edit tab.
3. click the yellow pencil or green "+" sign next to the "cover image" field. 
4. scroll down to see the image tags section.

Seems like going directly to: https://thor.dosomething.org/us/node/add/image correctly shows image tags.
#### Why This Matters

Tagging photos correctly allows us to keep a more robust database of photos on the site. 
#### Relevant Screenshots + Links

https://thor.dosomething.org/node/add/image/entityconnect-form-Rdwk4cgt5LVnphhPAuw35lBVOHXvBy_dwYRDXC0wKGI

![image](https://cloud.githubusercontent.com/assets/12396076/12827655/b4f4d412-cb4e-11e5-8330-5c1203ed7859.png)

**Comment by angaither** [comment] 2016-02-05 14:40
@namimody i noticed this too, but I don't think it's only image tags

**Comment by namimody** [comment] 2016-02-05 14:53
@angaither where else have you seen it?

**Comment by angaither** [comment] 2016-05-19 14:37
@namimody this can be fixed by creating global english translations of the image tags

**Comment by namimody** [comment] 2016-05-19 14:41
@angaither sweet!!! how do we do that? is that a product job or a dev job?

**Comment by angaither** [comment] 2016-05-19 14:44
@namimody they can be translated like any other content on the site, but visiting the term and hitting `translate`
e.g. https://www.dosomething.org/taxonomy/term/278/translate
it seems like the cause taxonomy was translated (https://www.dosomething.org/taxonomy/term/16/edit?destination=admin/structure/taxonomy/cause) 

***but this does make me think we fix a lot of things because global english is the default value on our site, and maybe we actually _don't_ want that to be true.

**Comment by namimody** [comment] 2016-05-20 14:20
@angaither I should still translate all taxonomy terms into all languages, right? regardless of the outcome of the "GL EN as default language" discussion?

**Comment by angaither** [comment] 2016-05-20 14:21
@namimody 👍 yeah that'll work

**Comment by angaither** [comment] 2016-05-20 14:21
or just change the language of the current ones to gl-english

**Comment by angaither** [comment] 2016-06-27 14:10
closing this one out too, it's a language issue, not a programatic issue

**Closed as completed by angaither** 2016-06-27 14:10 UTC
Labels: bug, #static-content, #translation
