### ISSUE TITLE
Mobile App Merge Tag Bug

### ISSUE THREAD

**Issue by marahml** [DoSomethingArchive/legacy-website#5870] opened 2015-12-02 18:59 UTC
K couldn't find the other issue, so here are the details: 
- When reporting back on the mobile app, users receive the email below
- The campaign name is not coming through, instead they are seeing CAMPAIGN TITLE

![image](https://cloud.githubusercontent.com/assets/6784628/11541484/7d2be6ea-9900-11e5-9da5-89dc65f01d9a.png)

cc @DeeZone 

---

There's another issue referencing this that I'm going to dig for! Just want to make sure this messaging work is accounted for in the Phoenix 2.1 milestone.

**Related / Duplicate**:
- https://github.com/DoSomething/phoenix/issues/5872

**Comment by sergiitk** [comment] 2016-01-12 19:49
Closing this as a duplicate of #5872.

**Closed as completed by sergiitk** 2016-01-12 19:49 UTC
Labels: #message-broker
