### ISSUE TITLE
Login can fail with blank mobile number

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#680] opened 2014-02-18 17:12 UTC
No matter what username I use, aschachter or admin, it tells me the password is incorrect.  I've reset the password so I know it's correct.

The error message, "Have you forgotten your password?" is linking me to http://stage.dosomething.org/user/password?name=rmohammed, suggesting that this is a caching issue.  When I try to add a query string into the URL however, I still get directed to the rmohammed reset link.

![screen shot 2014-02-18 at 12 13 35 pm](https://f.cloud.github.com/assets/1236811/2197821/67fd508e-98c0-11e3-913e-6953aadf0004.png)

**Comment by mshmsh5000** [comment] 2014-02-18 17:24
It's not Varnish. Still looking.

**Comment by mshmsh5000** [comment] 2014-02-18 17:52
Ravelle's login works. All other login attempts get processed as her user. For instance, if I log in as `mholford / mholford` (user / pass), then (a) the attempt fails, and (b) the failure is recorded in the `flood` table as Ravelle's user (uid=3).

**Comment by mshmsh5000** [comment] 2014-02-18 18:10
This is in the query log when I try to log in as myself:

`SELECT m.entity_id AS entity_id
FROM
field_data_field_mobile m
WHERE  (field_mobile_value = '')`

This matches entity_id 3, because that entry has no mobile number:

`+-------------+--------+---------+-----------+-------------+----------+-------+--------------------+---------------------+
| entity_type | bundle | deleted | entity_id | revision_id | language | delta | field_mobile_value | field_mobile_format |
+-------------+--------+---------+-----------+-------------+----------+-------+--------------------+---------------------+
| user        | user   |       0 |         3 |           3 | und      |     0 |                    | NULL                |
+-------------+--------+---------+-----------+-------------+----------+-------+--------------------+---------------------+`

Drupal then proceeds to try auth against uid=3, i.e., Ravelle.

@aaronschachter @angaither @barryclark This is application logic messing this up. Who's doing the mobile matching work?

**Comment by angaither** [comment] 2014-02-18 18:13
@mshmsh5000 I'll take a look into this.

**Comment by mshmsh5000** [comment] 2014-02-18 18:16
Thanks! Updated issue name and assigned to you.

**Comment by angaither** [comment] 2014-02-18 18:40
This is a duplicate of #665 
And was fixed with pull #666 

Once we pull in the latest changes on stage this issue should be resolved.

**Comment by aaronschachter** [comment] 2014-02-18 19:50
Can we add a test into dosomething_user.test to test for the fix?

**Closed as completed** 2014-02-19 17:36 UTC
