### ISSUE TITLE
email - campaign name merge tag not coming in properly on report back transacational

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#1340] opened 2014-03-17 19:44 UTC
On report back transactional email:

![image](https://f.cloud.github.com/assets/6330971/2440787/ce4027b2-ae0b-11e3-8db2-d1641ef60334.png)

However it is working on transactional email after I sign up for a campaign:
![image](https://f.cloud.github.com/assets/6330971/2440836/825c0824-ae0c-11e3-9ac8-d4cf0da290bb.png)

**Comment by aaronschachter** [comment] 2014-03-17 19:55
@DeeZone Looks like we've coded this to send through a CAMPAIGN_TITLE and not a CAMPAIGN_NAME.  is this a quick fix in the mandrill template?

**Comment by aaronschachter** [comment] 2014-03-17 20:14
This was an error in the email template. We've fixed in Mailchimp / Mandrill and confirmed works now:

![fuck yeah u did it](https://f.cloud.github.com/assets/1236811/2441191/b820b0d2-ae10-11e3-8a23-a797c5e01b35.png)

**Closed as completed by aaronschachter** 2014-03-17 20:14 UTC
Labels: @bender, priority-high, #transactional-emails

**Comment by deezone** [comment] 2014-03-17 20:32
@aaronschachter Confirmed, use the UI in MailChimp to update the template here: https://us4.admin.mailchimp.com/templates/#f:53

Once you've updated the template select "Send to Mandrill" in the drop down menu below each of the templates.
