### ISSUE TITLE
[Campaign Close] Tweets Field Collection

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#2380] opened 2014-05-30 15:05 UTC
Mocks here: https://sites.google.com/a/dosomething.org/dosomethinguxwiki/home/product-archive/campaign-template
- URL (of the actual twitter status e.g. https://twitter.com/dosomething/status/473463280053534720)
- Tweet Copy (Markdown)
- Image (should this be an image node for such a tiny lil image? file? grab magically from twitter?)

**Comment by angaither** [comment] 2014-06-03 17:00
@aaronschachter
@mikefantini  
what field types does this need? Is it a useraname? A link to a tweet? Photos?

**Comment by aaronschachter** [comment] 2014-06-03 17:08
Updated issue description.. definintely link to tweet.  The mocks are here https://sites.google.com/a/dosomething.org/dosomethinguxwiki/home/product-archive/campaign-template

The idea is that we'll be manually entering the Tweet copy to add our own classes around the stuff.. although @weerd any updates on what we can and can't do with displaying tweets, with regards to Twitter's rules of usage?

**Comment by angaither** [comment] 2014-06-03 17:49
According to them, we should be using the API to embed the tweets.
If we don't do that, we need to include all the requirements (including tweet actions.. which makes it more complex without the api)
![](http://cl.ly/image/3F0w062R0f3e/Screen%20Shot%202014-06-03%20at%201.48.17%20PM.png)
https://dev.twitter.com/terms/display-requirements

**Comment by aaronschachter** [comment] 2014-06-03 18:01
I would love to embed these for sure.  It doesn't seem worth it to build these out as different fields if Twitter can give us the no-go at any time.  Do they let us apply css to change the fonts?

**Comment by angaither** [comment] 2014-06-03 18:06
Looks like we can [change alignment and colors](https://dev.twitter.com/docs/embedded-tweets), but I don't think we can change the font. 
But like, it's a tweet, do we need to?

**Comment by aaronschachter** [comment] 2014-06-03 18:09
@barryclark @mikefantini Can you weigh in here?  This would be so much cleaner if we can just supply the Tweet URLs to embed.

**Comment by barryclark** [comment] 2014-06-03 18:55
I think that using [Embedded Tweets](https://dev.twitter.com/docs/embedded-tweets) sounds like the best ideas so long as we're fine with that from a design standpoint. 

@weerd Any thoughts/concerns?

**Comment by mikefantini** [comment] 2014-06-03 19:02
@angaither hold off on this right now... grabbing @crystalruthbell as soon as she's out of a meeting to sort through this

**Comment by mikefantini** [comment] 2014-06-03 19:18
@angaither confirmed with @crystalruthbell this is just a media style gallery; it's not specifically for tweets, that may be one of the uses but is not the intended functionality.

We just want a gallery that focuses less on the image and more on the content itself, this may be a tweet, it may be a quote from a celeb, it may be a fb post, etc.

We'll deal with the ramifications of copy/pasting tweets when we get there, but that's not what this gallery is solely intended for so we shouldn't build for that.

Instead, we just need this to have:
- gallery title
- gallery image
- image title
- image description

I don't think we'll need image URL but if it's easier to include that we can.

**Comment by angaither** [comment] 2014-06-03 19:44
@mikefantini so then, how is this different from the press section?

**Comment by mshmsh5000** [comment] 2014-06-03 20:07
General note: Dooooon't do custom tweet display, ever. It's not a good use of our time, and it annoys Twitter.

**Comment by mikefantini** [comment] 2014-06-03 21:00
ok so @crystalruthbell it seems like if we want to show someone giving us love on twitter specifically we'll have to show the tweet like so 

![image](https://cloud.githubusercontent.com/assets/6330971/3166526/cbc6a932-eb61-11e3-9325-25519b96d8e5.png)

we could probably put those in two columns still like we wanted to

are you cool with that stylistically or do you want us to just make the rule that we don't allow tweets in this section?

**Comment by barryclark** [comment] 2014-06-17 19:38
@mikefantini Do you know what the next steps are on this issue?

**Comment by crystalruthbell** [comment] 2014-06-17 19:52
I would rather us reference this as a quote and NOT link to twitter than use all their formatting restrictions. If anyone has more express concerned I'm happy to chat in person, not sure I fully understand still why we can ship as displayed in Tom's design below. 

http://screencast.com/t/nKHQvMZG

**Comment by barryclark** [comment] 2014-06-17 19:55
@crystalruthbell The reason we've been hesitant about it is that you're not allowed to quote tweets without using Twitter's official widget thing (that Mike screenshotted above). Otherwise you're basically stealing their content and displaying it on your own site. 

However:

a) We won't always be using this to display tweets.

and 

b) It seems unlikely that we'll run into problems with twitter. 

... so I'd be happy to close this and go with @tjrosario's current implementation. 

Is that cool with you @mikefantini?

**Comment by mikefantini** [comment] 2014-06-17 20:35
fine by me.. i know @mshmsh5000 had concerns but we could get around this I think just by not using the actual tweet and linking out to it?

and yeah it won't always be tweets so this may not even be an issue.

**Comment by tjrosario** [comment] 2014-06-18 14:59
Closing since we are sticking with current implementation.

**Comment by mikefantini** [comment] 2014-06-18 21:54
@tjrosario looking at some of the current content being put in @mshmsh5000 suggested you take a stab at implementing this tomorrow.

@crystalruthbell is going to grab some time on your calendar after you've had a chance to play with this a bit

**Comment by mikefantini** [comment] 2014-06-19 15:10
and re-closing based on @crystalruthbell's discussion with nancy

**Closed as completed by mikefantini** 2014-06-19 15:10 UTC
Labels: @fender, priority-high, #campaign-close

**Comment by barryclark** [comment] 2014-06-19 15:14
Reasoning was that we're not too concerned about the legal aspect and do want to maintain our design standards.

**Comment by crystalruthbell** [comment] 2014-06-19 15:34
Hey team, thanks for all your concerns and research around this. @barryclark good summary, we are going to move forward with the mocked design for this section understanding the legal because it best fits with scalable design principles. 

![screen shot 2014-06-19 at 11 33 49 am](https://cloud.githubusercontent.com/assets/6550604/3329456/2139fab0-f7c7-11e3-9c13-2338a9c3761b.png)
