### ISSUE TITLE
Inorrect Campaign Links on SMS Game Confirmation Page

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4836] opened 2015-08-12 22:14 UTC
![image](https://cloud.githubusercontent.com/assets/12396076/9238096/caa02c64-411d-11e5-9700-c2d76ccef013.png)

Thumb Wars, Bully Text, and Backseat Adviser links all link incorrectly to the "explore campaigns" page at this URL: 
https://www.dosomething.org/campaigns/thumb-wars%3Fsource%3Dcampaigns/5483/confirmation

They should link to their respective pitch pages.

**Comment by mikefantini** [comment] 2015-11-09 15:04
Duplicate of #5673. Sorry @namimody couldn't find this when I created the new issue.

**Closed as completed by mikefantini** 2015-11-09 15:04 UTC
Labels: bug
