### ISSUE TITLE
[Finder] Pagination

### ISSUE THREAD

**Issue by joolaay** [DoSomethingArchive/legacy-website#1679] opened 2014-04-08 01:14 UTC
Add "view more campaigns" to bottom of finder results.

Crystal's user testing confirmed that our demo loves scrolling. 
![homepage - see more campaigns](https://cloud.githubusercontent.com/assets/6331017/2639003/0fb53452-bebb-11e3-9fc1-fd254387ca83.jpg)

**Comment by mikefantini** [comment] 2014-04-09 19:42
closing this one since it's a duplicate of #1729

**Closed as completed by mikefantini** 2014-04-09 19:42 UTC
Labels: @fender, priority-high
