### ISSUE TITLE
Time Off on Hot Module Countdown

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4964] opened 2015-08-30 21:54 UTC
![image](https://cloud.githubusercontent.com/assets/12396076/9569674/f1fa68a8-4f3f-11e5-8081-e8533cb0492d.png)

At 5:52 PM EST on Aug 30, the hot module showed 2 hours left, when the back end is set for the campaign to end on Aug 31. (In UTC, it is still only 9:52 PM EST on Aug 30 -- not sure where time is being counted from.)

**Comment by angaither** [comment] 2015-08-31 13:35
@namimody I think this might be a duplicate of #4926 which @deadlybutter fixed on friday, but we haven't deployed yet

**Comment by namimody** [comment] 2015-08-31 14:16
Thanks for the update @angaither!

**Closed as completed** 2015-08-31 14:23 UTC
Labels: bug, #campaign-template
