### ISSUE TITLE
Can't create an account from /us/admin/people/create

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5566] opened 2015-10-21 02:07 UTC
Need to go to global URL (/admin/people/create).

**Comment by mikefantini** [comment] 2015-10-21 14:22
To be clear, you don't get redirected if you go to a base admin url (i.e. I can navigate to www.dosomething.org/admin/people/create) just fine from the US. The weird behavior happens when I go to www.dosomething.org, I get taken to www.dosomething.org/us and then when I try to navigate to /admin/people/create the /us/ persists, which seems to be causing the problems

**Comment by angaither** [comment] 2015-10-21 14:42
let's remove the country prefix from admin urls, I think it was just caused by our init hook logic and it's not there for any real reason

**Comment by angaither** [comment] 2015-10-22 20:59
@sheyd and @blisteringherb `mod_rewrite` vs `outbound_alter` we should chat. 
also refs #5482

**Comment by angaither** [comment] 2015-10-22 21:24
@sheyd is going to set up fastly/varnish bypass rule for any url with `admin` in it

**Comment by mikefantini** [comment] 2015-10-22 21:50
@angaither @sheyd does this mean we can apply similar logic to resolve #5482?

**Comment by sheyd** [comment] 2015-10-23 16:51
@angaither Rules setup on thor and you were right. Re-tracing the steps, and we still get `/us/admin` path entry. There is a SUPER hacky way to fix this in Fastly/Varnish, but I think it's better to do this in app.

**Comment by blisteringherb** [comment] 2015-10-28 17:42
@mikefantini Do you remember what errors you were running into or any additional details about the admin user or what failed? I just tried navigating to `https://thor.dosomething.org/us/admin/people/create`, and was able to create an account. I suspect that if this is only showing up in production, introducing all of the language, path and redirect settings into production should fix this. Also the dosomething_global_init() function seems to have been greatly simplified so that may have also fixed the issue.

**Comment by itsjoekent** [comment] 2015-10-28 17:50
Yeah when I rewrote the init function it should have fixed all of the problems like this. I'll try on my local as well just for the hell of it, but I think this is :ok: if it worked on Thor

**Comment by itsjoekent** [comment] 2015-10-28 17:52
Nope not working on my local. Both on /admin and /us/admin

Nope just worked on http://dev.dosomething.org:8888/admin/people/create wtf

**Comment by blisteringherb** [comment] 2015-10-28 19:57
@deadlybutter It should work fine at `/admin/people/create`, but Fantini was saying it doesn't work at `/us/admin/people/create`. When you tried on your local the second time, was it just at `/admin/people/create` or was it also at `/us/admin/people/create`?

**Comment by itsjoekent** [comment] 2015-10-28 20:37
Does not work from /us/admin

**Comment by itsjoekent** [comment] 2015-10-29 15:16
I re-opended because node admin pages still had prefixes, but they function ok so closing again

**Closed as completed by itsjoekent** 2015-10-29 15:16 UTC
Labels: @bender, #global

**Comment by mikefantini** [comment] 2015-10-29 15:35
Hmm yeah @blisteringherb there were no error messages, it just wasn't creating accounts.

If you were able to do it on thor then we're probably fine once we deploy global to prod.
