### ISSUE TITLE
Pitch page login should take user back to pitch page (not sign them up)

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#2580] opened 2014-06-18 14:02 UTC
Currently - user clicks login on any pitch page and it directs them to the action page after sign up or account creation. 

Aspirational - user logs in or creates an account and at the end of the auth flow the modal goes away and they are on the same pitch page and one click away from sign up.

**Comment by barryclark** [comment] 2014-06-18 14:30
@crystalruthbell Why would you want to add in another click after the user auths? They've already clicked that button. As a user I think I'd prefer the current implementation.

cc @mikefantini

**Comment by aaronschachter** [comment] 2014-06-18 14:33
The gotcha here is that they're not clicking on "Sign up" but the Login in the right hand corner.  You wouldnt' expect this to automatically sign you up for the campaign.  It's because both buttons are opening up the same login/register modal.  We'd need either separate forms for login/register+signup and just login/register.. or the ability to pass an argument to the form via click events on the two different links.

**Comment by DFurnes** [comment] 2014-06-18 14:35
~~I think the problem is if the user clicks the login button on the pitch page, it automatically signs them up even though they didn't click the blue "sign up" button.~~ @aaronschachter Yep.

One solution would be to have a hidden "clicked_signup_button" field on the login modal form that gets set to `1` through JavaScript if the user enters the form through the signup button. That way we don't need two forms.

**Comment by barryclark** [comment] 2014-06-18 14:37
Gottit, thanks.

**Comment by angaither** [comment] 2015-09-17 13:50
closing, duplicate of #1289

**Closed as completed by angaither** 2015-09-17 13:50 UTC
Labels: bug
