### ISSUE TITLE
Official Rules needs to show up on SMS games and scholarship handwritten font alignment needs fixing

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#3408] opened 2014-11-13 19:55 UTC
example https://www.dosomething.org/campaigns/science-sleuth (https://beta.dosomething.org/node/3478/edit)

@lkpttn please add mock of what this should look like here. thanks!

**Comment by lkpttn** [comment] 2014-11-13 20:36
@mikefantini 
![step 2](https://cloud.githubusercontent.com/assets/1865372/5038093/e37561d0-6b5a-11e4-83de-63707eee0709.png)

**Comment by mikefantini** [comment] 2014-11-13 22:19
@lkpttn like we talked about in person, can you please have the color of the Official Rules text match the color of the body copy above the fields?

**Comment by lkpttn** [comment] 2015-02-06 15:31
This appears to be functioning as intended on Science Sleuth.

**Comment by mikefantini** [comment] 2015-02-06 16:13
@lkpttn where are you seeing this?

I'm seeing on staging that this is still not functioning properly AND that "win a $1000 scholarship" alignment is off on http://staging.beta.dosomething.org/campaigns/sms-campaign

![image](https://cloud.githubusercontent.com/assets/6330971/6082636/e03babcc-adf0-11e4-800a-21a5ef57dceb.png)

**Comment by DFurnes** [comment] 2015-02-13 16:44
This is now fixed:

![screen shot 2015-02-13 at 11 42 59 am](https://cloud.githubusercontent.com/assets/583202/6191190/a8d635dc-b375-11e4-9c4f-0e6f6e4ed857.png)

**Closed as completed** 2015-02-13 16:44 UTC
Labels: @fender, #campaign-template, #sms-games
