### ISSUE TITLE
Last reportback item overrides all the items

### ISSUE THREAD

**Issue by itsjoekent** [DoSomethingArchive/legacy-website#4908] opened 2015-08-25 20:58 UTC
Let's say theres 3 reportback items, you flag the first two and promote the third. If you check the database for that reportback, FLAGGED = 0 and FLAGGED_REASON = NULL

Example: http://staging.beta.dosomething.org/admin/reportback/3069
- Flagged second RB item
- Promoted third RB item

What the DB shows

![screen shot 2015-08-25 at 4 57 27 pm](https://cloud.githubusercontent.com/assets/897368/9479216/677f7450-4b4a-11e5-8117-97a7da8d29c0.png)

I'm self assigning because on my local I've already fixed this

**Comment by angaither** [comment] 2015-08-26 13:17
duplicate of #4847

**Closed as completed** 2015-08-31 18:13 UTC
Labels: bug, @bender
