### ISSUE TITLE
Password Reset: Username Error

### ISSUE THREAD

**Issue by apatheticslacker** [DoSomethingArchive/legacy-website#2632] opened 2014-06-20 16:58 UTC
On prod, I opened up the link sent to my email account to reset my password and I was given this weird set of letters and numbers for my account's first name. 
![image](https://cloud.githubusercontent.com/assets/7773483/3343163/e78e2496-f89b-11e3-83e8-0a160f3fd6be.png)
Let me know if you got any questions on how this happened.

**Comment by aaronschachter** [comment] 2014-07-02 23:58
What we need to do for this one is override this string to NOT display the username, as it could be a UID, a password (see #2753), or an actual name (Aaron Schachter3).  Unfortunately I don't think we have access to user tokens like email or first name here, because the quickest solution would be to add a replacement string to our settings.php: https://github.com/DoSomething/dosomething/blob/dev/config/settings.php#L117

@mikefantini Can you provide text so someone can take this one?  Maybe something like "You're logged in!  Please change your password immediately."

**Comment by mikefantini** [comment] 2014-11-11 15:45
Yeah this should just be "You're logged in! Please change your password." Let's also update link of "Please change your password." from /user/[uid]/edit to /user/[uid]/edit?pass-reset-token=[token_value]. This would mimic the link that the user is taken to after she uses her one-time login.

**Comment by angaither** [comment] 2015-11-16 16:29
closing, duplicate of #2753

**Closed as completed by angaither** 2015-11-16 16:29 UTC
Labels: bug, @bender, #pw-reset
