### ISSUE TITLE
Odd Activity on DONATE Button Back End (Stripe)

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4838] opened 2015-08-12 23:39 UTC
Seems like something similar to automated tests are running on the site's donate button, resulting in hundreds of $1.00 failed donations from gibberish gmail addresses.

This is a problem because:
1) it makes it very difficult for Kenia to find real donations
2) sometime donations go through and then are cancelled
2a) Kenia needs to record all donation activity
2b) we are charged for fraudulent activity
3) our partnership with Alexander Wang launches in Sept and will rely on this page working well

More info to come on when this began.

**Comment by DFurnes** [comment] 2015-08-14 14:05
We are running automated tests on the Donate page through New Relics Synthetics. However, those use `newrelic@mailinator.com` as the test email address (and are also using test credit card numbers, so they I don't _think_ they should be counting as failures). They are for $1.00 though and run every hour.

**Comment by DFurnes** [comment] 2015-08-14 14:10
However, we're not in "test mode" on production (obviously!! :wink:) so maybe that's not actually okay?

/cc @aaronschachter

**Comment by aaronschachter** [comment] 2015-08-14 16:46
@DFurnes That sounds right, I don't think it's ok. The test card numbers are only good while in test mode: https://stripe.com/docs/testing#cards

**Comment by namimody** [comment] 2015-08-14 16:50
Thanks for popping in on this @DFurnes and @aaronschachter! Here is a screenshot of what Kenia is seeing happen - as you can tell, the email isn't newrelic@ and the tests are happening several times per hour. Does this look different than what you set up or is this because this should not be running on production? Thanks team.

![image](https://cloud.githubusercontent.com/assets/12396076/9278900/e46f0042-4281-11e5-9ecf-62a5b698da6f.png)

**Comment by aaronschachter** [comment] 2015-08-14 17:04
Matt set up the tests, but I think it's safe to say that doesn't look right.

**Comment by namimody** [comment] 2015-08-14 17:19
Thanks @aaronschachter. Because we have a partnership coming up in September that is going to route traffic to the Donate page, I think (@mikefantini, thoughts?) that we should address this next week. What information can I gather to help with figuring this out?

**Comment by mikefantini** [comment] 2015-08-17 16:22
@namimody we have incredibly high traffic happening since July 21st (~1000x normal traffic). can you check with marketing/finance if we've been doing a specific push? Most of this traffic seems to be direct traffic but only a small percentage of the direct traffic are entrances.

There have also been several visits from https://99tests.com/. This could be related to the tests that have been running. Let's chat about this in slack and see if we can get in touch with them to stop testing this page.

also worth getting in touch with stripe and seeing if there is anything on their end that can be done to prevent this from happening.

also @sergii-tkachenko has added the donate page to our out of scope section for cobalt.io

can you also find out when these weird transactions started happening and post that here

**Comment by sergiitk** [comment] 2015-08-17 16:41
Hey @namimody, regarding item 1:
You can filter out unsuccessful donations like this: 

![image](https://cloud.githubusercontent.com/assets/672669/9310344/d9df6d04-4517-11e5-991b-ad5b097229be.png)

**Comment by sergiitk** [comment] 2015-08-17 16:46
Oh, it looks like it costs us $15 for every transaction disputed not in our favor:

> Yes, you incur a $15.00 fee when there is a dispute on one of your transactions. If the dispute is resolved in your favor, however, we refund the fee.
> https://stripe.com/help/disputes#is-there-a-fee-for-disputes

**Comment by sergiitk** [comment] 2015-08-17 16:49
I'd suggest to decline transactions with wrong CVC: 
https://dashboard.stripe.com/account
![image](https://cloud.githubusercontent.com/assets/672669/9310534/ee3893e2-4518-11e5-9cad-be9e5fc11b11.png)

If we receive only US donation, it is also possible to decline charges that fail zip code verification.

cc @aaronschachter

**Comment by sergiitk** [comment] 2015-08-17 16:52
Also, here's decent documentation what to do and how to avoid with fraudulent transactions:
https://support.stripe.com/questions/avoiding-fraud-and-disputes

**Comment by namimody** [comment] 2015-08-17 19:00
Additional notes: 
- high traffic began July 22nd, from "direct"
- of traffic between July 22nd and now, only 43 pageviews (0 entrances...) came from 99tests.com, but 99tests.com does not appear in sources for the three months prior to July 22nd
- 99tests.come first appears as a source on July 29th
- gibberish emails start appearing 7/22/2015

Kenia is out today, but I'll circle back with her tomorrow to see if we have an account rep that we can hop on the phone with. I'm hesitant to turn on any auto-decline features because room for human error is high for those fields.

![7e693ee8-44f2-11e5-8b0f-012a45a76cae](https://cloud.githubusercontent.com/assets/583202/9387660/9d4b0be0-472f-11e5-8b33-8df3207fd4a7.jpg)

**Comment by namimody** [comment] 2015-08-18 15:28
Update: Emailed Stripe 8/18 and waiting to hear back (no phone support).

@aaronschachter and @DFurnes if this should not be running on production, how/when can we change it to run on staging? Thanks!

**Comment by namimody** [comment] 2015-08-20 15:49
Update: no response from Stripe as of 8/20 at 1!:50 am. Called 99tests.com and spoke to Praveen who will let us know in 12-24 hours if something is targeting our site and will get it stopped right now, if so. He has my email address.

**Comment by namimody** [comment] 2015-08-21 19:25
Update: Called 99tests.com again and they said they aren't doing anything on our site.

Stripe responded: There's not much we can do on our end to prevent this third party from testing on your account, however you should be able to screen successful fraud payments on your account by searching for low dollar donations linked to email addresses like DFGJDF@gmail.com (based off what the 3rd party is using). You should refund these to avoid chargebacks.

You may also want to consider working with a third party fraud prevention system like MaxMind, Kount, or Siftscience:

http://www.maxmind.com/en/home
http://www.kount.com/
https://siftscience.com/

Sorry I couldn't give you much more help. Depending on the limitations of your integration, you may be able to block potential test charges made on your site. You may also want to add CAPTCHA [1]  test to prevent a 3rd party from automating charges to your account.

Next Steps: I think we can either:
- change settings so that if CSV or zip code verification fails then we won't take donation and see if that changes things (the only thing is that this could also be human error for real donations)
- we add CAPTCHA as a donation step
- we ban $1 and $5 donations ("test" donations now seem to have increased to $5)

Let's please talk about this at sprint planning on Monday. Thanks!

**Comment by namimody** [comment] 2015-08-24 15:50
Update: turned on Stripe setting that will decline donations where zip code or CVC verification fails at around 10:15 am EST (1:15 PM / 13:15 UTC) on 8.24. Will monitor to see if this changes test behavior

(If a genuine donor messes up their CVV, they get a banner notification that their card was declined. This activity doesn't seem to show up on the Stripe backend.)

**Comment by namimody** [comment] 2015-08-24 18:27
![image](https://cloud.githubusercontent.com/assets/12396076/9448713/2aead0f4-4a6c-11e5-8a90-20a6878bc10a.png)

Donations are still getting through despite the additional "decline donation" obstacles.

![image](https://cloud.githubusercontent.com/assets/12396076/9448737/4573bb3e-4a6c-11e5-9ccd-aed279f6223f.png)

I've gone ahead (with Kenia's permission) and refunded all successful but fake donations going back to through July that allowed me to.

**Comment by namimody** [comment] 2015-08-24 18:44
<img src="https://github.trello.services/images/trello-icon.png" width="12" height="12"> [DONATE Button Activity](https://trello.com/c/pRq0gaGc/1466-donate-button-activity)

**Comment by angaither** [comment] 2015-08-24 20:25
@deadlybutter we are going to go the honeypot solution for now.

**Comment by DFurnes** [comment] 2015-08-24 20:30
![technical diagram](https://cloud.githubusercontent.com/assets/583202/9451564/74f8677c-4a7d-11e5-9824-3b2af22007e5.JPG)

**Comment by itsjoekent** [comment] 2015-08-24 20:38
![image](https://cloud.githubusercontent.com/assets/897368/9451766/9bc20ace-4a7e-11e5-9b2f-51d967193bf4.png)

this is relevant and further clarifies the issue, because the attacker is Winnie the pooh and the honey pot is clearly attracting their attention.

**Comment by weerd** [comment] 2015-08-24 20:40
> this is relevant and further clarifies the issue, because the attacker is Winnie the pooh and the honey pot is clearly attracting there attention.

grammar :cop: 
*their

**Comment by namimody** [comment] 2015-08-24 21:46
Update: refunded all "fake" donations (gibberish email, low amount with generic email at high frequency) through May to avoid the potential for them to be marked as fraudulent and for us to be charged.

**Comment by angaither** [comment] 2015-08-25 13:32
nami 4 prez :clap:

**Comment by DFurnes** [comment] 2015-08-25 15:23
I think we should leave this issue open for discussion until we're sure the issue is resolved. Re-opening.

**Comment by itsjoekent** [comment] 2015-08-25 15:31
to track if the :honey_pot: is working we can also look at stathat, relevant stat is `drupal - Donate - honeypot`

**Comment by itsjoekent** [comment] 2015-08-28 14:34
all of the current ideas & things we've tried to counter this

https://trello.com/b/F6UrBLr1

**Comment by namimody** [comment] 2015-08-28 14:38
Update: changed DONATE CTA to link to Paypal (V. Stripe modal) at 10:35 AM EST on 8.28. Will monitor PayPal backend to see if "donations" continue.

**Comment by itsjoekent** [comment] 2015-08-31 14:51
update

https://dosomething.slack.com/archives/donate/p1441029627000012

> @namimody: haha yes @joe that is what i meant sorry — the fake donations seemed to have stopped!

**Comment by namimody** [comment] 2015-09-14 15:31
PayPal account was looking fine until 9/12. (Screenshot in Trello > FRUGS > DONATE Button Activity)

Refunding this and continuing to check daily.

**Comment by angaither** [comment] 2015-11-16 22:11
closing this until we switch back from paypal

**Closed as completed by angaither** 2015-11-16 22:11 UTC
Labels: #donate
