### ISSUE TITLE
Markdown - bold disabled 

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#1143] opened 2014-03-11 16:35 UTC
Intro text section. Tried both `**bold**` and `<strong>bold</strong>`. Neither output bold html tags.

**Comment by aaronschachter** [comment] 2014-03-11 16:46
This is by design, to prevent use and abuse.  Allows HTML tags are configured in  admin/config/content/formats/markdown, but we would need to update the `dosomething_settings` feature in order to make any changes to this.

**Comment by barryclark** [comment] 2014-03-12 14:09
@aaronschachter So you cant bold things inline, by design?

**Comment by aaronschachter** [comment] 2014-03-12 14:10
Yes, but we can easily change the text format to allow that. The idea in not allowing was restricting people from going bold crazy.

**Comment by barryclark** [comment] 2014-03-12 14:13
BOLD MOVE @aaronschachter

**Comment by DFurnes** [comment] 2014-03-12 14:13
:b: :bangbang:

**Comment by mikefantini** [comment] 2014-03-12 14:14
+1 on not having bold.. let's see what individual issues with that come up.

**Comment by barryclark** [comment] 2014-03-12 14:14
I'm reviewing static content stuff with Julie and Crystal this afternoon, so will see if there's a real need for it based on the static content pages we have planned.

**Comment by barryclark** [comment] 2014-03-13 00:23
@julielorch Want to flag this above with you. Is there anywhere that we'll absolutely need to be able to bold things in static content?

**Comment by mikefantini** [comment] 2014-03-26 21:04
closing unless someone comes up with a good argument to enable

**Closed as completed by mikefantini** 2014-03-26 21:04 UTC
Labels: @bender, priority-low
