### ISSUE TITLE
Password Reset - Bugs

### ISSUE THREAD

**Issue by marahml** [DoSomethingArchive/legacy-website#1287] opened 2014-03-14 22:12 UTC
1 - after I go through the forgot PW flow and click to send pw reset email, it just takes me back to login screen with no "we sent you an email" message

2 - after i click on the one-time link in the reset PW flow, I am taken to a screen to reset my PW that already has my login info pre-populated. That'll definitely confuse users

**Comment by deezone** [comment] 2014-03-14 22:26
@marahml @mikefantini Can this be spec-ed out for what the expected behaviour should be?

**Comment by mikefantini** [comment] 2014-03-14 22:32
@DeeZone I will definitely update, nothing to worry about before Tuesday. Moving to the back log for now.

**Comment by barryclark** [comment] 2014-06-26 19:15
1. Is a duplicate of of #1005 
2. Is fixed now

**Closed as completed by barryclark** 2014-06-26 19:15 UTC
