### ISSUE TITLE
Archiving Activity Makes Default RB Examples + Featured Members on Live Closed State Disappear

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#5140] opened 2015-09-17 01:28 UTC
![image](https://cloud.githubusercontent.com/assets/12396076/9922784/794df8ce-5cba-11e5-81eb-858837b3ff77.png)

![image](https://cloud.githubusercontent.com/assets/12396076/9922805/d5844b98-5cba-11e5-868f-47673e7c2c30.png)

If activity is archived, default RB images should still show on active tab, and featured member photos should still appear if campaign activity is archived to a published run.

**Comment by namimody** [comment] 2015-09-17 01:34
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;mIUHWsJz&#x2F;1485-archiving-activity-makes-default-rb-examples-featured-members-on-closed-state-disappear"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Archiving Activity Makes Default RB Examples + Featured Members on Closed State Disappear</a>

**Comment by angaither** [comment] 2015-11-17 14:37
closing, duplicate of #4068

**Closed as completed by angaither** 2015-11-17 14:37 UTC

**Comment by namimody** [comment] 2015-11-17 15:48
Hey @angaither -- just want to clarify on this -- this issue is about how archiving activity affects the appearance of a published closed state, while #4068 is about displaying archived photos of an old run in the PROVE IT section of a published open campaign. Is the code the same in these instances?

**Comment by angaither** [comment] 2015-11-17 15:52
@namimody yup, should be! in both cases the reportbacks don't show up because they are no longer associated with the original campaign nid, they get tied to the run.

**Comment by namimody** [comment] 2015-11-17 16:10
Ahh! Okay thanks for clarifying @angaither. I'm just going to add that when we fix 4068 we should check that the closed state also works.

Perhaps unrelated -- but when we archive activity, all the example RBs get wiped from the PROVE IT section of the campaign, like below (Derrius added one photo just now, which is why 1 photo is showing, but after archiving activity the space next to the photo upload modal is entirely blank) - should this be a separate issue?
![image](https://cloud.githubusercontent.com/assets/12396076/11216786/2789c5ae-8d1b-11e5-9f72-bfb7b14739ab.png)

**Comment by namimody** [comment] 2015-11-19 15:11
@angaither just circling back on this :)
