### ISSUE TITLE
Reportback Cropping: image_gd_create() error 

### ISSUE THREAD

**Issue by sbsmith86** [DoSomethingArchive/legacy-website#3712] opened 2015-01-12 21:21 UTC
There is a bug that sometimes gets shown when cropping and image. It seems to be tied to when the image cropping script things that the crop area selected does not fully cover the image. 
![image_gd_create](https://cloud.githubusercontent.com/assets/1700409/5711264/08d53b80-9a77-11e4-8a80-480643b22019.jpg)

**Comment by barryclark** [comment] 2015-01-14 16:48
Sometimes able to go out of the bounding box of the image too.

**Comment by mikefantini** [comment] 2015-01-28 17:43
also seeing this error now:

![image](https://cloud.githubusercontent.com/assets/6330971/5943211/058cd99e-a6eb-11e4-8018-4675c8efed44.png)

not sure if it's related to the crop but adding per request in hipchat

**Comment by barryclark** [comment] 2015-01-28 18:31
We need steps to be able to replicate this.

**Comment by mikefantini** [comment] 2015-02-04 15:03
TSG was seeing these errors: ![image](https://cloud.githubusercontent.com/assets/6330971/6042664/b00e7972-ac54-11e4-89f0-22d50cf70e19.png)

Related trello card here: https://trello.com/c/H8pMpV6B

**Comment by barryclark** [comment] 2015-02-04 16:46
@aaronschachter We're stumped with this one, would you be able to help debug? These errors occur directly after submitting an image—but only about 10% of the time. We're trying to get solid steps to recreate too.

**Comment by aaronschachter** [comment] 2015-02-04 16:49
I thought this occurs when the crop box goes outside of the image?

**Comment by barryclark** [comment] 2015-02-04 16:57
@aaronschachter We don't think that's the case any more... but trying to get steps to be able to 100% replicate this.

**Comment by mikefantini** [comment] 2015-02-04 19:29
@aaronschachter from the specialist guild:

1) This seemed to occur randomly when doing TCs 7 through 9 (see image below). It did not seem like a specific set of steps would cause the problem.

2) Yes, it was only in IE8 and IE9.

3) Unfortunately, we fairly randomly generated user accounts sometimes several per browser, so no one can recall the specific accounts. We will try to reproduce the problem and note the uid down.

![image](https://cloud.githubusercontent.com/assets/6330971/6047845/2a2a3820-ac7a-11e4-81bb-7c567e90a397.png)

**Comment by aaronschachter** [comment] 2015-02-05 16:20
Not having any luck replicating this locally in Chrome or Firefox.

**Comment by weerd** [comment] 2015-02-10 16:17
I can successfully replicate this issue with a specific scenario.

It appears to happen when there's no lack of support for the File API, or we fake the JS into thinking that the browser doesn't support the File API.

What I suspect is that in the backend, when the form is submitted, one of the PHP cropping functions is expecting certain data to be passed along but because the file API wasn't supported (or faked non-support) the image crop stuff didn't need to run and maybe some essential data is not passed...

Here's a list of screenshots of errors I got in the logs when replicating the issue:

![image](https://cloud.githubusercontent.com/assets/105849/6130836/fc2aef78-b115-11e4-9922-75816ab9767f.png)

![image](https://cloud.githubusercontent.com/assets/105849/6130839/06bd949a-b116-11e4-891f-793f1c5f145d.png)

![image](https://cloud.githubusercontent.com/assets/105849/6130846/131768ce-b116-11e4-88c5-53d7baeead9c.png)

![image](https://cloud.githubusercontent.com/assets/105849/6130859/23e0a378-b116-11e4-8b86-9f1197bd5fbf.png)

![image](https://cloud.githubusercontent.com/assets/105849/6130904/72ed9a48-b116-11e4-9131-36ed632c7e0b.png)

![image](https://cloud.githubusercontent.com/assets/105849/6130897/68946612-b116-11e4-8d05-8b42b0344f3b.png)

**Comment by aaronschachter** [comment] 2015-02-10 16:21
@weerd Can you give more details about what this means? or how to replicate?

> It appears to happen when there's no lack of support for the File API, or we fake the JS into thinking that the browser doesn't support the File API.

**Comment by sbsmith86** [comment] 2015-02-10 16:21
:+1: :100: great find!

**Comment by weerd** [comment] 2015-02-10 22:33
Sure. 
1. Both feature flags are active (Show New Reportback & Allow Cropping of Images), 
2. But using a browser that doesn't support the File API (api we're using to help with cropping the reportback images),  such as IE8 or IE9.
3. Attempt to select image and submit reportback in said older browser, using simpler (non-cropping) interface.
4. Submission happens, but we see those errors.

My suspicion is that there's a PHP function used when cropping feature flag is turned on, that is expecting certain parameters, but they don't get passed because they can't be collected if File API is not available (for example, maybe related to rotation).

Does this make more sense @aaronschachter ?

**Comment by aaronschachter** [comment] 2015-02-10 22:42
Ya! thanks for clarifying @weerd.

**Comment by barryclark** [comment] 2015-02-17 18:44
Would you be able to take a look at this one @aaronschachter?

**Comment by weerd** [comment] 2015-02-18 22:18
Reassigning to you @barryclark, then just pass along to @aaronschachter if he's going to be tackling this bendery issue.

**Comment by aaronschachter** [comment] 2015-02-18 22:22
No @weerd we assigned it to you! :) i have no idea what the File API stuff with older browser is... also i'm not exactly set up to test in IE...

**Comment by weerd** [comment] 2015-02-18 22:35
Oh, haha @aaronschachter. Hokay. I can give it a whirl. It's not specifically a File API thing, but more of a PHP is expecting parameters that it's not getting and thus crapping out. Thought it was more bendery, but I'll take a crack at it :)

**Comment by barryclark** [comment] 2015-02-18 23:14
![](http://testingthoughts.com/ericproegler/wp-content/uploads/2015/01/schneideryou-can-do-it.jpg) @weerd!

**Comment by weerd** [comment] 2015-02-18 23:20
LOL :)

**Comment by aaronschachter** [comment] 2015-02-25 15:39
I'm able to replicate this locally in Chrome with what must be some out of date JS (I pulled down from dev but have not run a `ds grunt`). Hoping this might help debug.

When I first load the page, I see an `Uncaught TypeError: Cannot read property 'cropEnabled' of undefined` within Chrome Insepctor.
when I upload a file, the error still exists and the page looks like this:
![screen shot 2015-02-25 at 10 37 21 am](https://cloud.githubusercontent.com/assets/1236811/6373723/7d45e408-bcda-11e4-8bcc-8c9bf4836e06.png)

Upon submitting, these errors are output:

Warning: imagecreatetruecolor() [function.imagecreatetruecolor]: Invalid image dimensions in image_gd_create_tmp() (line 297 of /var/www/vagrant/html/modules/system/image.gd.inc).
Warning: imagecolorallocate() expects parameter 1 to be resource, boolean given in image_gd_create_tmp() (line 321 of /var/www/vagrant/html/modules/system/image.gd.inc).
Warning: imagefill() expects parameter 1 to be resource, boolean given in image_gd_create_tmp() (line 321 of /var/www/vagrant/html/modules/system/image.gd.inc).
Warning: imagecopyresampled() expects parameter 1 to be resource, boolean given in image_gd_crop() (line 185 of /var/www/vagrant/html/modules/system/image.gd.inc).

**Closed as completed** 2015-02-27 15:08 UTC
Labels: @fender, priority-medium
