### ISSUE TITLE
'Likes' going into negative numbers 

### ISSUE THREAD

**Issue by jessleenyc** [DoSomethingArchive/legacy-website#6573] opened 2016-06-08 19:41 UTC
#### Current Behavior

Kudos is going into negative numbers when you reload the page after you've liked something. 
#### Desired Behavior

Kudos should retain the same number of likes. 
#### Steps to Replicate

1.Navigate to staging
2.Click on any active campaign
3.'like' a photo
4.refresh page
5. click on emoji multiple times
#### Why This Matters

Negative 'likes' make no sense.

![screen shot 2016-06-08 at 3 05 05 pm](https://cloud.githubusercontent.com/assets/14931921/15907277/769c09d0-2d8a-11e6-93e9-d3a78dd495d9.png)

**Comment by angaither** [comment] 2016-06-09 17:32
looks like this is because when a page loads, it doesn't have a `kid` so it's `POST`ing to create a new record and getting a `FALSE` so it looks like the numbers go negative

**Comment by weerd** [comment] 2016-06-09 17:37
This might be related.... but I removed the `data-kid` attribute cause it seemed like it was a duplicate attribute here: https://github.com/DoSomething/phoenix/pull/6563/files#diff-c661ff64a81c86b6b235e5c3dddee4acL19

**Comment by weerd** [comment] 2016-06-09 17:37
There were both `data-kudo-id` and `data-kid`. If removing the `data-kid` is the issue, then maybe I can just point the JS to use `data-kudo-id` instead?

**Comment by angaither** [comment] 2016-06-09 17:38
`data-kudo-id` perhaps not the most aptly named field is the term id of the kudo
and `kid` is the actually record row in the table. 
that's ~totally~  what we are missing

**Comment by weerd** [comment] 2016-06-09 17:40
oh! Yeah, super confusing. Totally thought it was just the same @_@

I can make a fix for that with the PR I'm already doing for the view more. Wanna assign this to me?

**Comment by angaither** [comment] 2016-06-09 17:42
I gotz it

**Comment by weerd** [comment] 2016-06-09 17:42
k

**Comment by jessleenyc** [comment] 2016-06-10 15:31
@weerd our intern Sam was able to break this again and bring kudos into negative numbers. See screenshot below. I replicated by clicking the heart multiple times as well. 

![screen shot 2016-06-10 at 11 14 20 am](https://cloud.githubusercontent.com/assets/14931921/15969609/c9f71f0a-2efe-11e6-990e-d570733a920d.png)

also, @deadlybutter i don't think the purple heart should be purple with 0 likes -- do you forsee this bug, where a heart is colored in when it shouldn't be, carrying over to our new graphics? i can create a new ticket or wait to test the new images. let me know!

**Comment by weerd** [comment] 2016-06-10 15:34
Okie doke. Working on adding the kudos to the view more gallery and almost done on that front. Can take a look at this right after :) Thanks for flagging and all the tests! Appreciate it 😄

**Comment by angaither** [comment] 2016-06-13 14:36
@jessleenyc I'm not seeing this happen anymore, is it still an issue?

**Comment by jessleenyc** [comment] 2016-06-13 15:12
@angaither just checked again and it's still an issue if you click on a heart multiple times, rapidly. 

![screen shot 2016-06-13 at 11 11 31 am](https://cloud.githubusercontent.com/assets/14931921/16012484/b0282afa-3157-11e6-93d3-06adb88077aa.png)

**Comment by weerd** [comment] 2016-06-13 15:14
Confirmed. Spamming the button will go negative. I can see if I can add something to disable the button until the AJAX request returns.

**Closed as completed** 2016-06-13 18:07 UTC
Labels: bug, #reportback, #kudos
