### ISSUE TITLE
Search results show "hunt" but not "the hunt"

### ISSUE THREAD

**Issue by crystalruthbell** [DoSomethingArchive/legacy-website#2387] opened 2014-05-30 18:54 UTC
![screen shot 2014-05-30 at 2 51 55 pm](https://cloud.githubusercontent.com/assets/6550604/3134916/d965379a-e82b-11e3-9f19-ae84219fec70.png)

**Comment by aaronschachter** [comment] 2014-05-30 18:56
This likely a duplicate of #2095.

**Comment by blisteringherb** [comment] 2014-06-04 14:33
A quick update, I am looking at this, and the issue is in how we have Drupal configured with search.  Searching directly against Solr without any biases yields the same result when searching for "Hunt" and "The Hunt".

**Comment by blisteringherb** [comment] 2014-06-06 17:43
This should be fixed in production now.  There are some biases that were overridden, but those should be good now.  Both 'hunt' and 'the hunt' show The Hunt at the top of the search results.

**Closed as completed by blisteringherb** 2014-06-06 17:43 UTC
Labels: bug, @bender, #campaign-collections
