### ISSUE TITLE
GL EN user being taken to /us/ content

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#5695] opened 2015-11-03 16:35 UTC
As a user in Brazil (who we are currently treating as GL EN), when I navigate to thor.dosomething.org I remain on the base alias, which is good.

When I click on Veggie Surprise I am taken to the GL EN translation, which is good.

However, once I go to create an account, I am then taken to the US English translation, which is incorrect behavior.

Also when I click through on the email I receive, I am taken to the US English translation, which is also incorrect behavior.

**Comment by mikefantini** [comment] 2015-11-03 16:36
Also this is the user I experienced this issue with. His language is appropriately set as Global English:

UID: 3230281

**Comment by mikefantini** [comment] 2015-11-03 17:02
The same thing happens for a user located in Costa Rica.

**Comment by mikefantini** [comment] 2015-11-03 18:10
I'm also able to navigate directly to the GL EN Veggie Surprise logged in _after_ I'm already logged in (i.e. when I go to thor.dosomething.org/campaigns/veggie-surprise it doesn't redirect me to thor.dosomething.org/us/campaigns/veggie-surprise).

**Comment by mikefantini** [comment] 2015-11-03 18:14
Also if I go to another another campaign after I'm already logged in from the homepage (i.e. thor.dosomething.org/campaigns/free-pee) I'm taken to the GL EN pitch page. Then when I go to sign up, I am taken to the GL EN action page.

So it's only occurring on auth. And happens _both_ when creating a new account _and_ when logging in to an existing account.

**Comment by angaither** [comment] 2015-11-03 18:15
@blisteringherb is trying with a revert of [this commit](https://github.com/deadlybutter/phoenix/commit/7028ddde3a6b3d891a146407974d1196563baf39)

think that's the culprit

**Comment by itsjoekent** [comment] 2015-11-05 19:14
this appears to also be fixed by https://github.com/DoSomething/phoenix/pull/5721

**Comment by itsjoekent** [comment] 2015-11-05 20:05
confirmed, seems to be fixed

**Closed as completed by itsjoekent** 2015-11-05 20:05 UTC
Labels: bug, @bender, BLOCKER, #global
