### ISSUE TITLE
Ensure GL EN Users Should Be GL EN

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#6159] opened 2016-02-09 00:38 UTC
#### Current Behavior

It seems like some US members have their language set as Global English.
#### Desired Behavior

Want to make sure that all users have the correct language set on their profile based on their actual location.
#### Steps to Replicate

First we need to just figure out if the GL EN language setting is actually incorrect. I think we can do this by pulling users with addresses in their profile and comparing it to what their language is set to.
#### Why This Matters

For data purposes, US users should have a profile set to US EN.
#### Relevant Screenshots + Links

UIDs: 1981451 (was GL EN, I changed it to US EN when she reported that she was having trouble logging into her account from anything but an incognito window), 2553817

@mikefantini could you add the couple other UIDs that you've seen affected? Thanks!

**Comment by namimody** [comment] 2016-02-10 22:17
2553817

**Comment by mikefantini** [comment] 2016-02-18 20:03
Yeah so for https://www.dosomething.org/us/user/2553817/edit she is 100% located in the US and yet her language is set to GL EN

**Comment by blisteringherb** [comment] 2016-02-18 21:50
@angaither We store the user's country in Northstar, correct? Would you be able to give me a hint on how to query Northstar so I can cross check users with global english set as their profile language in Drupal with US users?

**Comment by angaither** [comment] 2016-02-18 21:51
@blisteringherb yeah, we for sure store country, but not language in NS. 
lemme think about this query hereeeeeeee

**Comment by DFurnes** [comment] 2016-02-18 21:53
@blisteringherb If you want anything (other than language!) from Northstar, [Aurora](https://aurora.dosomething.org) is probably your best bet. If you log in & then ping me in Slack, I can give you admin privileges.

**Comment by blisteringherb** [comment] 2016-02-18 21:56
@DFurnes Thanks!

**Comment by angaither** [comment] 2016-02-18 21:57
@blisteringherb also, duh it's mongo so query like
`db.users.find({drupal_id:"100001"});`
`db.users.find({country:"US"});`
etc etc

**Comment by blisteringherb** [comment] 2016-03-02 17:15
I've set up Fastly logging to S3 to make sure we're getting what we expect at the edge.

**Comment by blisteringherb** [comment] 2016-03-09 18:13
@sergii-tkachenko Would you happen to have any ideas about why this might be happening?

**Comment by sergiitk** [comment] 2016-03-09 18:22
Wrong Fastly headers for mobile users? cc @deadlybutter

**Comment by itsjoekent** [comment] 2016-03-09 18:26
hmmm, im not even sure how to test that one. also seems weird thats the cause.

i get if the phone location is quite a distance off, but i feel like it should be getting country right?

**Comment by sergiitk** [comment] 2016-03-09 18:30
As I understand, Fastly doesn't actually locate the phone, it traces back phone IP. Which, for mobile phones, is always dynamic and also often is out of known range. So it's getting detected incorrectly or even not detected at all.

**Comment by itsjoekent** [comment] 2016-03-09 18:33
well the only other options I can think of then

1) base it on browser language setting
2) give user ability to change language

**Comment by sergiitk** [comment] 2016-03-09 18:35
I agree with 2).

**Comment by blisteringherb** [comment] 2016-03-09 18:35
@mikefantini @namimody Do we have any sense of how widespread the issue is?

**Comment by mikefantini** [comment] 2016-03-09 19:51
@blisteringherb not sure. Can you pull how many users have language as GL EN and we can see if that tracks with non-us traffic to campaign pages in a significant way or not?

**Comment by angaither** [comment] 2016-03-14 15:21
some users are getting `en-global` set even though their county both fastly & drupal is US
![](https://i.imgur.com/RS7Sq1M.png)

**Comment by mikefantini** [comment] 2016-03-14 16:32
Information that would be helpful to know to understand scope of the problem:
1. # of users with language set to GL EN (again if this is way out of whack with non-US traffic it will tell us something)
2. # of users who have country set to US and language set to anything other than EN.

**Comment by DFurnes** [comment] 2016-05-18 17:57
If this is due to #6442, it should be fixed if the Niche consumer is updated to send the `country` parameter added in #6463 (which will in turn now set the right language for that country code).

/cc @DeeZone

**Comment by angaither** [comment] 2016-05-18 17:58
I think we should update this issue (or open a new one) to backfill and fix users who have the wrong language

**Comment by deezone** [comment] 2016-05-18 19:10
@DFurnes @angaither Based on the Phoenix Create User endpoint: https://github.com/DoSomething/phoenix/wiki/API#create-a-user

The default language for all Niche users imported should be `US` even though it's not been provided in the in the current `POST`: https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_api/resources/member_resource.inc#L175

**Comment by DFurnes** [comment] 2016-05-18 19:18
@DeeZone Yep, that was the parameter that I mentioned was added in #6463. If all Niche users are coming from the US, then it's safe to omit and let it use the default value.

**Comment by deezone** [comment] 2016-05-18 19:30
Nice... I should have "clicky clicked" your reference link before making my comment.

**Comment by deezone** [comment] 2016-05-19 00:18
@DFurnes  Both `mobile` and `country` are now being submitted to Phoenix for new user requests:
https://github.com/DoSomething/mbc-user-import/blob/master/src/MBC_UserImport_Source_Niche.php#L135-L151

**Comment by deezone** [comment] 2016-05-19 00:20
@DFurnes 

Time for `mbc-user-import` to use Northstar? If so, I'll try to get it on our roadmap for sooner than later.

**Comment by DFurnes** [comment] 2016-05-19 13:54
@DeeZone I think that'd be a great idea! Let me know if there's anything I can do to help.

**Comment by ngjo** [comment] 2016-07-11 19:11
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;dvxiFwzO&#x2F;1537-https-dosomethingorg1-zendesk-com-agent-tickets-155081"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> https:&#x2F;&#x2F;dosomethingorg1.zendesk.com&#x2F;agent&#x2F;tickets&#x2F;155081</a>

**Comment by namimody** [comment] 2016-07-11 19:14
Update: another interesting case: https://dosomething.slack.com/archives/campaigns-team/p1456757093000085 (ticket no longer exists in ZenDesk)

Re: Thanks for signing up for Yo Teach!
Hey,
im very excited to take part in this, the only problem is that whenever I log in the page is written in spanish and i dont know how to change it back to English. So if you could please help! 
thank you,
[name]

@ngjo pulled up two potential member profiles for them (based on their name, not their email, because we don't have access to that):

https://www.dosomething.org/us/user/2548171/edit
https://www.dosomething.org/us/user/2253052/edit

both profiles have their language set as GL EN, so it is also bizarre that this member is seeing Spanish. We'll discuss this behavior further on the 25th during the global bugs sync. Thanks!

**Comment by angaither** [comment] 2016-08-04 19:19
this was fixed when we updated the country/language settings in the api #6463

**Comment by angaither** [comment] 2016-08-25 17:38
Ahhh well shite. 
Apparently a bunch (3,345,289 people) DON'T have a language set at all. which means the script I ran for #6748 actually didn't get the people who have NO LANGUAGE.

**Closed as completed** 2016-08-25 17:59 UTC
Labels: bug, @bender, discussion, #global, large, NO
