### ISSUE TITLE
Unable to delete campaign signup

### ISSUE THREAD

**Issue by deezone** [DoSomethingArchive/legacy-website#2257] opened 2014-05-21 18:03 UTC
Due to what appears to be fender funkiness, see screen capture:
http://screencast.com/t/jmpzcmN4k

It's not possible to select the Delete button to remove a campaign signup for an admin user.

**Comment by aaronschachter** [comment] 2014-05-21 18:09
duplicate of #2201

**Comment by aaronschachter** [comment] 2014-05-21 18:10
@DeeZone I get around this by using Chrome Inspector and changing the position of the site nav.

**Closed as completed by aaronschachter** 2014-05-21 18:09 UTC
Labels: @fender
