### ISSUE TITLE
[SMS game] - no texts sent + error message received

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2406] opened 2014-06-03 15:21 UTC
Got this error message when testing out the SMS Game http://staging.beta.dosomething.org/campaigns/bully-text-0. Also no messages were sent to either alpha or beta.

![image](https://cloud.githubusercontent.com/assets/6330971/3162118/5c3f26ea-eb32-11e3-8032-d81f2e571fdd.png)

cc: @aaronschachter @angaither @weerd

**Comment by mikefantini** [comment] 2014-06-03 15:21
also the opt-in path is set up on staging:

![image](https://cloud.githubusercontent.com/assets/6330971/3162180/cb729812-eb32-11e3-94bf-c025367f8f47.png)

**Comment by aaronschachter** [comment] 2014-06-03 16:37
@mikefantini @jonuy Do these opt-in paths actually exist in Mobilecommons?  And can we confirm they have been inputted correctly?

I've just tried testing the dev node, http://staging.beta.dosomething.org/node/1199, and got sent a text.

My suspicion is that the paths are not set in Mobilecommons or have been entered incorrectly. If this is the issue, we can keep this issue open to add code to catch the errors that are happening with a cleaner "Whoops someone entered the wrong thing" message.
]

**Comment by mikefantini** [comment] 2014-06-03 16:49
@aaronschachter it appears to be correct:
- alpha: https://dosomething.mcommons.com/campaigns/121235/opt_in_paths/161989
- beta: https://dosomething.mcommons.com/campaigns/121235/opt_in_paths/160921

**Comment by aaronschachter** [comment] 2014-06-03 17:22
I've tested http://staging.beta.dosomething.org/campaigns/bully-text-0 and it works for me, @barryclark confirmed he received a text.  Can we get some more people testing this to see if we can replicate.

**Comment by jonuy** [comment] 2014-06-03 17:30
Works for me. Both alpha and beta received texts.

**Comment by mikefantini** [comment] 2014-06-03 18:08
Just got the error again when testing as "authuser" on http://staging.beta.dosomething.org/campaigns/bully-text-0

![image](https://cloud.githubusercontent.com/assets/6330971/3164427/0aeb9b26-eb4a-11e3-9560-4b27912c0661.png)

**Comment by angaither** [comment] 2014-06-03 18:12
I agree with @mikefantini I was able to submit when I was logged out, but with my user account I got the same error.

**Comment by mikefantini** [comment] 2014-06-03 18:16
yeah worked for me logged out but tried on multiple accounts logged in with no luck:
- uid 1700179
- uid 145

**Comment by aaronschachter** [comment] 2014-06-03 18:16
@uy were you logged in when you tested? i've just tested as logged in and it works.

**Comment by mikefantini** [comment] 2014-06-03 18:19
@aaronschachter what uid did you test with?

The two I tested with above don't have a mobile number attached to the user account, does the one that worked for you have a cell number saved to the profile?

**Comment by aaronschachter** [comment] 2014-06-03 18:21
yes, i used my stage uid 5 and it has a #.  this woudl explain it though, i think this is the offending code, which we should just remove.

```
  // Check if an account exists for the given alpha mobile.
  // An anonymous user is able to submit the form, but they may still have an account.
  if ($account = dosomething_user_get_user_by_mobile($values['alpha_mobile'])) {
    // Create a signup for the account.
    // If $account happens to be the logged in user, it's okay.
    // dosomething_signup_create will check if a signup exists before creating.
    dosomething_signup_create($nid, $account->uid);
  }
```

**Comment by mikefantini** [comment] 2014-06-03 18:28
ok cool. @aaronschachter want to take that out for now and we can revisit after we get this out to usertesting.com?

**Comment by aaronschachter** [comment] 2014-06-03 18:31
sure i can take this one, assigning to myself.

**Comment by jonuy** [comment] 2014-06-03 19:31
Sounds like you guys got it... but just for the sake of responding, I tested while logged out.

**Comment by aaronschachter** [comment] 2014-06-03 20:17
Still looking into this, removing code I thought would fix is not fixing. I've been able to replicate: Only seems to happen if a logged in user submits the form and does NOT have a mobile set on their user profile.

**Closed as completed** 2014-06-03 21:20 UTC
Labels: @bender, BLOCKER, priority-high, #sms-games
